// Atlas definitions. Every map is data: regions (approximate polygons), routes (legs of named places with references),
// places (with the chapters they appear in), notes on disputes, and the chapters that should link here.
import { P, PLACES } from './places.js';
const poly = (name, color, ring, opts={}) => ({ name, color, ring, ...opts });
const leg = (label, stops, refs, opts={}) => ({ label, stops, refs, ...opts });

export const MAPS = [
{
  id:'exodus', title:'The Exodus from Egypt', shelf:'atlas',
  subtitle:'Out of Egypt, to the mountain, and forty years to the Jordan',
  intro:'Israel left Rameses in the eastern Nile delta, crossed the sea, camped at Sinai for almost a year, failed at Kadesh, wandered for a generation, and finally came round Edom and Moab to the plains opposite Jericho. Numbers 33 lists forty two camps; the major ones are here.',
  view:{ center:[34.3,30.2], zoom:6.3 },
  books:['Exodus','Numbers','Deuteronomy'],
  regions:[
    poly('Edom','#c9a227',[[35.45,31.0],[35.95,31.0],[36.05,30.5],[35.7,29.6],[35.3,29.6],[35.42,30.3]]),
    poly('Moab','#8a6aa6',[[35.55,31.05],[36.05,31.02],[36.15,31.55],[35.6,31.55]]),
    poly('Ammon','#d9a441',[[35.8,31.6],[36.3,31.55],[36.4,32.1],[35.9,32.15]]),
  ],
  labels:[['Goshen',[31.85,30.75]],['Wilderness of Shur',[32.9,30.0]],['Wilderness of Sin',[33.4,28.75]],['Wilderness of Paran',[34.4,29.9]],['Wilderness of Zin',[35.0,30.75]],['Midian',[35.4,28.3]],['Canaan',[35.1,31.9]],['Negev',[34.75,31.0]],['Red Sea',[33.4,27.9]],['Great Sea',[32.6,31.4]]],
  routes:[
    { id:'trad', label:'Traditional southern route', color:'#d69282', legs:[
      leg('Out of Egypt',['Rameses','Succoth','Etham','Pi-hahiroth'],['Exodus 12:37','Exodus 13:20','Exodus 14:2']),
      leg('Through the sea to the mountain',['Pi-hahiroth','Marah','Elim','Wilderness of Sin','Rephidim','Mount Sinai'],['Exodus 14:21-31','Exodus 15:23','Exodus 15:27','Exodus 16:1','Exodus 17:1','Exodus 19:1']),
      leg('Sinai to Kadesh',['Mount Sinai','Hazeroth','Kadesh-barnea'],['Numbers 10:12','Numbers 11:35','Numbers 13:26']),
      leg('Forty years in the wilderness',['Kadesh-barnea','Ezion-geber','Kadesh-barnea'],['Numbers 14:33-34','Numbers 33:35-36','Deuteronomy 2:1'],{ dashed:true }),
      leg('Round Edom to the plains of Moab',['Kadesh-barnea','Mount Hor','Punon','Zered','Arnon','Dibon','Mount Nebo','Plains of Moab'],['Numbers 20:22-29','Numbers 21:4','Numbers 21:12-13','Numbers 33:45','Deuteronomy 34:1','Numbers 22:1']),
      leg('Into the land',['Plains of Moab','Jericho'],['Joshua 3:14-17','Joshua 6']),
    ]},
    { id:'alt', label:'Alternative route (Aqaba crossing, Sinai in Arabia)', color:'#62b6c9', dashed:true, legs:[
      leg('Across the peninsula to the Gulf of Aqaba',['Rameses','Succoth','Etham','Nuweiba'],['Exodus 13:18','Exodus 14:2']),
      leg('Crossing to Midian and the mountain',['Nuweiba','Jabal al-Lawz'],['Exodus 3:1','Galatians 4:25']),
      leg('North to Kadesh',['Jabal al-Lawz','Ezion-geber','Kadesh-barnea'],['Deuteronomy 1:2']),
    ]},
  ],
  places:[
    ['Rameses',['Exodus 1:11','Exodus 12:37'],'Store city where Israel laboured and from which the exodus began.'],
    ['Pithom',['Exodus 1:11'],'The other store city built by Israelite labour.'],
    ['Succoth',['Exodus 12:37','Numbers 33:5'],'First camp after leaving Rameses.'],
    ['Etham',['Exodus 13:20'],'Edge of the wilderness.'],
    ['Pi-hahiroth',['Exodus 14:2','Exodus 14:9'],'Where Israel camped, hemmed in, before the sea opened.'],
    ['Marah',['Exodus 15:23'],'Bitter water made sweet.'],
    ['Elim',['Exodus 15:27'],'Twelve springs and seventy palms.'],
    ['Wilderness of Sin',['Exodus 16:1'],'Manna and quail begin.'],
    ['Rephidim',['Exodus 17:1-16'],'Water from the rock; the battle with Amalek.'],
    ['Mount Sinai',['Exodus 19:1','Exodus 19 to 40','Numbers 10:11'],'Eleven months at the mountain: the covenant, the law, the tabernacle.'],
    ['Hazeroth',['Numbers 11:35','Numbers 12:16'],'Miriam and Aaron challenge Moses.'],
    ['Kadesh-barnea',['Numbers 13:26','Numbers 20:1','Deuteronomy 1:46'],'The spies return; Israel refuses to enter. Miriam dies here.'],
    ['Ezion-geber',['Numbers 33:35','Deuteronomy 2:8'],'Head of the Gulf of Aqaba, on the wandering route.'],
    ['Mount Hor',['Numbers 20:22-29'],'Aaron dies and Eleazar becomes high priest.'],
    ['Punon',['Numbers 33:42'],'In the Arabah, near the copper mines of Feinan.'],
    ['Zered',['Numbers 21:12','Deuteronomy 2:13-14'],'Crossing the Zered marked the end of the thirty eight years.'],
    ['Arnon',['Numbers 21:13'],'Border between Moab and the Amorite kingdom of Sihon.'],
    ['Dibon',['Numbers 21:30','Numbers 33:45'],'Later the capital of Moab.'],
    ['Heshbon',['Numbers 21:25-26'],'Sihon’s capital, taken by Israel.'],
    ['Mount Nebo',['Deuteronomy 32:49','Deuteronomy 34:1-6'],'Moses sees the land and dies.'],
    ['Plains of Moab',['Numbers 22:1','Numbers 25:1','Deuteronomy 1:5'],'Balaam, the census, and Moses’ farewell sermons.'],
    ['Jericho',['Joshua 2','Joshua 6'],'First city in the land.'],
    ['Nuweiba',['Exodus 14'],'Proposed alternative crossing point across the Gulf of Aqaba.'],
    ['Jabal al-Lawz',['Exodus 19'],'Proposed alternative Mount Sinai in ancient Midian.'],
    ['Memphis',['Isaiah 19:13'],'Egypt’s ancient capital.'],
    ['Heliopolis',['Genesis 41:45'],'On, the sun city; Joseph’s wife came from its priest.'],
  ],
  notes:[
    ['Where was the sea?','The Hebrew is yam suph, "sea of reeds". The traditional view puts the crossing at the northern end of the Gulf of Suez or one of the lakes north of it. A minority view puts it at the Gulf of Aqaba near Nuweiba, with Sinai in Arabia. Both are drawn; the text does not settle it.'],
    ['Which mountain?','Jebel Musa has been venerated as Sinai since the fourth century, but nothing in Exodus fixes it. Paul says Sinai is "in Arabia" (Galatians 4:25), which in his day included the Sinai peninsula. Jabal al-Lawz is the leading alternative.'],
    ['How many people?','Exodus 12:37 counts six hundred thousand men on foot. Some read the number as a census figure, some as a literal total near two million with families, some as a later multiplication. Every map of the route depends on that answer.'],
    ['When?','An early date around 1446 BC follows 1 Kings 6:1; a late date around 1270 BC fits Rameses as a city name and the archaeology of the Judges period. The route is the same either way.'],
  ],
},
{
  id:'tribes', title:'The Twelve Tribes', shelf:'atlas',
  subtitle:'The land allotted under Joshua, and the six cities of refuge',
  intro:'Joshua 13 to 21 divides the land by lot. Two and a half tribes settled east of the Jordan, nine and a half west. Levi received no territory, only forty eight cities, six of them cities of refuge. Boundaries here follow the biblical descriptions and are approximate, as the text itself often is.',
  view:{ center:[35.4,32.2], zoom:7.4 },
  books:['Joshua','Judges'],
  regions:[
    poly('Asher','#6a8f6a',[[34.95,32.75],[35.25,32.72],[35.3,32.95],[35.32,33.2],[35.25,33.4],[35.1,33.4],[35.05,33.1],[34.98,32.9]],{ ref:'Joshua 19:24-31' }),
    poly('Naphtali','#4d6f95',[[35.25,32.72],[35.55,32.7],[35.62,32.85],[35.6,33.05],[35.66,33.3],[35.4,33.4],[35.25,33.4],[35.32,33.2],[35.3,32.95]],{ ref:'Joshua 19:32-39' }),
    poly('Zebulun','#b08d3f',[[35.1,32.6],[35.48,32.6],[35.5,32.72],[35.25,32.72],[35.02,32.72]],{ ref:'Joshua 19:10-16' }),
    poly('Issachar','#c96a3f',[[35.2,32.45],[35.58,32.42],[35.6,32.62],[35.48,32.6],[35.2,32.6]],{ ref:'Joshua 19:17-23' }),
    poly('Manasseh (west)','#7a5c96',[[34.9,32.2],[35.55,32.2],[35.58,32.42],[35.2,32.45],[35.2,32.6],[35.1,32.6],[35.02,32.72],[34.95,32.75],[34.9,32.55]],{ ref:'Joshua 17:1-13' }),
    poly('Ephraim','#d9a441',[[34.95,31.95],[35.55,31.98],[35.55,32.2],[34.9,32.2]],{ ref:'Joshua 16:5-10' }),
    poly('Dan','#8fb3dc',[[34.7,31.85],[35.05,31.83],[35.05,32.05],[34.95,31.95],[34.9,32.2],[34.8,32.1]],{ ref:'Joshua 19:40-48' }),
    poly('Benjamin','#a35b3f',[[35.05,31.78],[35.55,31.75],[35.55,31.98],[34.95,31.95],[35.05,31.83]],{ ref:'Joshua 18:11-28' }),
    poly('Judah','#8a3b2e',[[34.7,31.35],[35.5,31.3],[35.55,31.75],[35.05,31.78],[34.75,31.85],[34.55,31.6]],{ ref:'Joshua 15' }),
    poly('Simeon','#c9b79a',[[34.5,31.05],[35.15,31.05],[35.2,31.3],[34.7,31.35],[34.5,31.3]],{ ref:'Joshua 19:1-9' }),
    poly('Reuben','#5c7f5c',[[35.55,31.47],[36.05,31.45],[36.05,31.82],[35.6,31.85]],{ ref:'Joshua 13:15-23' }),
    poly('Gad','#9a7526',[[35.6,31.85],[36.05,31.82],[36.05,32.2],[35.75,32.3],[35.65,32.7],[35.58,32.7]],{ ref:'Joshua 13:24-28' }),
    poly('Manasseh (east)','#7a5c96',[[35.65,32.7],[35.75,32.3],[36.05,32.2],[36.25,32.3],[36.3,33.0],[35.75,33.2],[35.62,33.0]],{ ref:'Joshua 13:29-31' }),
  ],
  labels:[['Philistines',[34.45,31.55]],['Phoenicians',[35.25,33.5]],['Moab',[35.85,31.25]],['Ammon',[36.2,31.95]],['Aram',[36.3,33.3]],['Great Sea',[34.45,32.4]]],
  routes:[],
  places:[
    ['Shechem',['Joshua 8:30-35','Joshua 24:1','Joshua 20:7'],'Covenant renewal between Ebal and Gerizim; a city of refuge.',{ refuge:true }],
    ['Kedesh',['Joshua 20:7'],'City of refuge in Galilee.',{ refuge:true }],
    ['Hebron',['Joshua 14:13-15','Joshua 20:7'],'Caleb’s inheritance; a city of refuge.',{ refuge:true }],
    ['Golan',['Joshua 20:8'],'City of refuge in Bashan.',{ refuge:true }],
    ['Ramoth-gilead',['Joshua 20:8'],'City of refuge in Gilead.',{ refuge:true }],
    ['Bezer',['Joshua 20:8'],'City of refuge on the plateau of Reuben.',{ refuge:true }],
    ['Shiloh',['Joshua 18:1','1 Samuel 1:3'],'The tabernacle stood here for the Judges period.'],
    ['Gilgal',['Joshua 4:19','Joshua 5:9'],'First camp in the land; the covenant sign renewed.'],
    ['Jericho',['Joshua 6'],'The first city taken.'],
    ['Ai',['Joshua 7 to 8'],'Defeat, then victory.'],
    ['Gibeon',['Joshua 9 to 10'],'The treaty city; the sun stands still.'],
    ['Hazor',['Joshua 11:10'],'Head of the northern kingdoms, burned by Joshua.'],
    ['Bethel',['Judges 1:22-26','Judges 20:18'],'Taken by Ephraim; a sanctuary in the Judges period.'],
    ['Dan',['Judges 18:27-29'],'Laish, renamed when the tribe of Dan migrated north.'],
    ['Jerusalem',['Joshua 15:63','Judges 1:21','2 Samuel 5:6-9'],'Jebusite city on Judah’s border, not taken until David.'],
    ['Beersheba',['Genesis 21:31','Judges 20:1'],'Southern limit: "from Dan to Beersheba".'],
    ['Megiddo',['Judges 1:27','Judges 5:19'],'Canaanite stronghold guarding the pass into Jezreel.'],
    ['Beth-shean',['Joshua 17:11','1 Samuel 31:10'],'Unconquered Canaanite city; Saul’s body hung on its wall.'],
    ['Gaza',['Joshua 13:3','Judges 16:21'],'Philistine city; Samson’s last act.'],
    ['Ashdod',['Joshua 13:3','1 Samuel 5:1'],'Philistine city where the ark was taken.'],
    ['Joppa',['Joshua 19:46'],'Dan’s allotted port, never held.'],
    ['Mount Ebal',['Deuteronomy 27:13','Joshua 8:30'],'Mountain of the curse; Joshua’s altar.'],
    ['Mount Gerizim',['Deuteronomy 27:12'],'Mountain of the blessing.'],
    ['Mount Tabor',['Judges 4:6'],'Barak gathers against Sisera.'],
    ['Mount Carmel',['Joshua 19:26'],'Asher’s southern border on the coast.'],
    ['Rabbah',['Joshua 13:25','2 Samuel 12:26'],'Ammonite capital, on Gad’s eastern edge.'],
    ['Heshbon',['Joshua 13:17'],'Reuben’s chief city, former capital of Sihon.'],
    ['Mahanaim',['Joshua 13:26','2 Samuel 2:8'],'Gad’s northern border; later Ish-bosheth’s and David’s refuge.'],
  ],
  notes:[
    ['Why twelve and a half?','Joseph received a double portion through his sons Ephraim and Manasseh, and Manasseh straddled the Jordan. Levi received cities, not land, so the count of territories comes to twelve even with Levi left out.'],
    ['Cities of refuge','Numbers 35 and Joshua 20 set aside six Levitical cities, three on each side of the Jordan, where someone who killed accidentally could flee from the avenger until trial. They are marked with a ring.'],
    ['Dan moved','Dan was allotted the Shephelah near the Philistines but could not hold it. Judges 18 records the tribe migrating north to Laish at the foot of Hermon, which is why "Dan" ends up at both ends of the land.'],
    ['Boundaries are approximate','Joshua describes borders by listing towns and landmarks, many of which are unidentified. Every tribal map, including this one, fills the gaps with judgment.'],
  ],
},
{
  id:'divided-kingdom', title:'Israel and Judah', shelf:'atlas',
  subtitle:'The divided kingdom and its neighbours, about 850 BC',
  intro:'After Solomon the kingdom split. Ten tribes followed Jeroboam in the north with a capital eventually at Samaria; Judah and Benjamin kept David’s line in Jerusalem. For two centuries the two kingdoms fought, allied, and were squeezed by Aram, Assyria and the small states across the Jordan, until Samaria fell in 722 BC and Jerusalem in 586.',
  view:{ center:[35.5,32.1], zoom:7.2 },
  books:['1 Kings','2 Kings','2 Chronicles','Amos','Hosea','Isaiah','Micah'],
  regions:[
    poly('Israel','#4d6f95',[[34.9,31.95],[35.55,31.95],[35.6,31.85],[36.05,31.85],[36.1,32.6],[35.6,33.15],[35.3,33.2],[35.05,33.05],[34.95,32.6]],{ ref:'1 Kings 12:20' }),
    poly('Judah','#8a3b2e',[[34.75,31.1],[35.55,31.15],[35.55,31.95],[34.9,31.95],[34.75,31.7]],{ ref:'1 Kings 12:21' }),
    poly('Philistia','#a35b3f',[[34.2,31.3],[34.75,31.3],[34.75,31.7],[34.9,31.95],[34.75,32.1],[34.45,31.6]]),
    poly('Phoenicia','#6a8f6a',[[35.0,33.05],[35.3,33.1],[35.4,33.6],[35.2,33.7]]),
    poly('Aram-Damascus','#62b6c9',[[35.7,33.15],[36.1,32.6],[36.6,32.9],[36.7,33.7],[36.0,33.8]]),
    poly('Ammon','#d9a441',[[35.8,31.6],[36.3,31.55],[36.4,32.1],[35.9,32.15]]),
    poly('Moab','#8a6aa6',[[35.55,31.05],[36.05,31.02],[36.15,31.55],[35.6,31.55]]),
    poly('Edom','#c9a227',[[35.45,31.0],[35.95,31.0],[36.05,30.5],[35.7,29.6],[35.3,29.6],[35.42,30.3]]),
  ],
  labels:[['Assyria (beyond)',[36.6,34.0]],['Great Sea',[34.45,32.5]]],
  routes:[],
  places:[
    ['Samaria',['1 Kings 16:24','2 Kings 17:5-6'],'Omri’s capital; fell to Assyria in 722 BC.',{ capital:true }],
    ['Jerusalem',['1 Kings 12:27','2 Kings 25:8-10'],'David’s city and the temple; fell to Babylon in 586 BC.',{ capital:true }],
    ['Shechem',['1 Kings 12:1','1 Kings 12:25'],'Where the kingdom split; Jeroboam’s first capital.'],
    ['Tirzah',['1 Kings 15:21','1 Kings 16:23'],'Northern capital before Samaria.'],
    ['Dan',['1 Kings 12:29'],'Site of one of Jeroboam’s golden calves.'],
    ['Bethel',['1 Kings 12:29','Amos 7:13'],'The other calf; the royal sanctuary Amos denounced.'],
    ['Jezreel',['1 Kings 21:1','2 Kings 9:30-37'],'Ahab’s winter palace; Naboth’s vineyard; Jezebel’s death.'],
    ['Mount Carmel',['1 Kings 18:19-40'],'Elijah against the prophets of Baal.'],
    ['Megiddo',['2 Kings 9:27','2 Kings 23:29'],'Where Ahaziah fled and where Josiah died.'],
    ['Ramoth-gilead',['1 Kings 22:3-38','2 Kings 9:14'],'Contested with Aram; Ahab’s death; Jehu anointed.'],
    ['Beth-shean',['1 Kings 4:12'],'Solomon’s district town.'],
    ['Gilgal',['2 Kings 2:1','Hosea 4:15'],'Prophetic centre, later a place of false worship.'],
    ['Mizpah',['1 Kings 15:22'],'Fortified by Asa on Judah’s northern border.'],
    ['Lachish',['2 Kings 14:19','2 Kings 18:14'],'Judah’s second city; Sennacherib’s siege.'],
    ['Beersheba',['1 Kings 19:3','Amos 5:5'],'Judah’s southern limit.'],
    ['Hebron',['2 Chronicles 11:10'],'Fortified by Rehoboam.'],
    ['Gath',['2 Kings 12:17','2 Chronicles 11:8'],'Philistine city taken by Hazael and fortified by Rehoboam.'],
    ['Ekron',['2 Kings 1:2'],'Baal-zebub’s shrine, consulted by Ahaziah.'],
    ['Tyre',['1 Kings 16:31','Ezekiel 26'],'Phoenician power; Jezebel was a Sidonian princess.'],
    ['Sidon',['1 Kings 16:31','1 Kings 17:9'],'Elijah stayed at Zarephath in Sidon’s territory.'],
    ['Damascus',['1 Kings 20','2 Kings 8:7-15','2 Kings 16:9'],'Capital of Aram; Ben-hadad and Hazael; taken by Assyria in 732.'],
    ['Rabbah',['2 Samuel 12:26','Amos 1:14'],'Ammon’s capital.'],
    ['Dibon',['2 Kings 3:4'],'Moab; the Mesha stele found here records Moab’s revolt.'],
    ['Kir-hareseth',['2 Kings 3:25'],'Moab’s stronghold besieged by Israel and Judah.'],
    ['Bozrah',['Amos 1:12','Isaiah 63:1'],'Edom’s capital.'],
    ['Petra',['2 Kings 14:7'],'Sela, taken by Amaziah.'],
    ['Mount Gilboa',['1 Samuel 31:1'],'Where Saul fell, a generation before the split.'],
  ],
  notes:[
    ['Two kingdoms, two calendars','The books of Kings date each king by the other kingdom’s reigns, and the two courts counted years differently. That is why scholarly date tables for this period differ by a year or two.'],
    ['Nineteen kings, no good ones','Every northern king "did evil in the eyes of the LORD" by the standard of Kings, because all kept Jeroboam’s calves. Judah had twenty rulers, eight of them judged good, all in David’s line.'],
    ['The Mesha stele','A Moabite inscription found at Dibon in 1868 tells 2 Kings 3 from Moab’s side and names Omri, Israel and Yahweh. It is one of the earliest outside witnesses to the kingdom.'],
  ],
},
{
  id:'jesus', title:'The Land in the Days of Jesus', shelf:'atlas',
  subtitle:'Galilee, Samaria, Judea and the regions around them',
  intro:'Herod’s kingdom was split among his sons at his death. Galilee and Perea went to Antipas, the north east to Philip, and Judea and Samaria to Archelaus, then to Roman governors like Pilate. Most of Jesus’ ministry happened in the small triangle of towns on the north shore of the lake. The Decapolis and Phoenicia were Gentile country he entered on purpose.',
  view:{ center:[35.4,32.3], zoom:7.6 },
  books:['Matthew','Mark','Luke','John'],
  regions:[
    poly('Galilee','#4d6f95',[[35.05,32.55],[35.6,32.6],[35.6,33.1],[35.15,33.1]]),
    poly('Samaria','#b08d3f',[[34.9,31.95],[35.5,31.95],[35.55,32.55],[35.05,32.55]]),
    poly('Judea','#8a3b2e',[[34.75,31.3],[35.5,31.35],[35.5,31.95],[34.9,31.95],[34.75,31.7]]),
    poly('Perea','#6a8f6a',[[35.55,31.45],[35.95,31.45],[35.95,32.35],[35.6,32.4]]),
    poly('Decapolis','#7a5c96',[[35.6,32.4],[36.1,32.35],[36.15,32.85],[35.65,32.9]]),
    poly('Tetrarchy of Philip','#62b6c9',[[35.65,32.9],[36.2,32.9],[36.3,33.5],[35.7,33.5]]),
  ],
  labels:[['Phoenicia',[35.25,33.5]],['Idumea',[34.95,31.15]],['Nabatea',[36.1,31.2]],['Great Sea',[34.45,32.4]]],
  routes:[
    { id:'north', label:'Ministry around the lake', color:'#d69282', legs:[
      leg('Nazareth to Capernaum',['Nazareth','Cana','Capernaum'],['Matthew 4:13','John 2:1','Luke 4:31']),
      leg('Across the lake and back',['Capernaum','Kursi','Bethsaida','Capernaum'],['Matthew 8:23-34','Mark 6:45','Luke 9:10']),
    ]},
    { id:'gentile', label:'Into Gentile country', color:'#62b6c9', legs:[
      leg('To Tyre and Sidon, back through the Decapolis',['Capernaum',[35.45,33.05],'Tyre','Sidon',[35.78,33.38],[35.82,32.85],'Gadara','Capernaum'],['Matthew 15:21','Mark 7:24-31']),
      leg('To Caesarea Philippi and the mountain',['Capernaum','Bethsaida',[35.66,33.1],'Caesarea Philippi',[35.6,33.0],[35.5,32.85],'Mount Tabor'],['Matthew 16:13','Matthew 17:1']),
    ]},
    { id:'samaria', label:'Through Samaria', color:'#d9a441', legs:[
      leg('Judea to Galilee by way of Sychar',['Bethany beyond the Jordan','Sychar','Cana'],['John 4:3-5','John 4:46']),
    ]},
    { id:'final', label:'The last journey to Jerusalem', color:'#ece7dc', legs:[
      leg('Galilee to Jerusalem through Perea',['Capernaum',[35.58,32.7],[35.57,32.3],[35.56,31.95],'Bethany beyond the Jordan','Jericho','Bethany','Jerusalem'],['Matthew 19:1','Matthew 20:29','Matthew 21:1','Matthew 21:17']),
      leg('Emmaus',['Jerusalem','Emmaus'],['Luke 24:13']),
    ]},
  ],
  places:[
    ['Bethlehem',['Matthew 2:1','Luke 2:4'],'Birthplace, five miles south of Jerusalem.'],
    ['Nazareth',['Matthew 2:23','Luke 4:16-30'],'Home town; rejected him in its synagogue.'],
    ['Sepphoris',[],'Antipas’ capital an hour’s walk from Nazareth; never named in the Gospels, but Joseph likely worked there.'],
    ['Cana',['John 2:1-11','John 4:46'],'Water into wine; the official’s son healed from a distance.'],
    ['Capernaum',['Matthew 4:13','Matthew 9:1','Mark 2:1'],'His base; Peter’s house; the synagogue.'],
    ['Bethsaida',['Matthew 11:21','Mark 8:22','John 1:44'],'Home of Peter, Andrew and Philip; a blind man healed.'],
    ['Chorazin',['Matthew 11:21'],'Condemned with Bethsaida for unbelief.'],
    ['Magdala',['Matthew 15:39','Luke 8:2'],'Magadan; Mary Magdalene’s town.'],
    ['Tiberias',['John 6:23'],'Antipas’ new capital on the lake; Jesus is never recorded entering it.'],
    ['Kursi',['Matthew 8:28-34','Mark 5:1-20'],'The demons and the pigs, on the Gentile shore.'],
    ['Gadara',['Matthew 8:28'],'Decapolis city; its territory reached the lake.'],
    ['Nain',['Luke 7:11-17'],'The widow’s son raised.'],
    ['Mount Tabor',['Matthew 17:1-9'],'Traditional mountain of the transfiguration; Hermon is the other candidate.'],
    ['Caesarea Philippi',['Matthew 16:13-20'],'Peter’s confession at the foot of Hermon.'],
    ['Mount Hermon',['Matthew 17:1'],'Snow capped; a candidate for the transfiguration.'],
    ['Tyre',['Matthew 15:21','Mark 7:24'],'The Syrophoenician woman’s daughter healed.'],
    ['Sidon',['Mark 7:31'],'Northern limit of his travels.'],
    ['Sychar',['John 4:5-42'],'Jacob’s well; the Samaritan woman.'],
    ['Samaria',[],'Sebaste, Herod’s rebuilt city; the region’s name.'],
    ['Ephraim',['John 11:54'],'Where Jesus withdrew after raising Lazarus.'],
    ['Jericho',['Matthew 20:29','Luke 19:1-10'],'Zacchaeus; Bartimaeus.'],
    ['Bethany beyond the Jordan',['John 1:28','John 10:40'],'John’s baptising; Jesus’ own baptism.'],
    ['Bethany',['Matthew 21:17','John 11:1','John 12:1'],'Home of Mary, Martha and Lazarus; his lodging in Passion Week.'],
    ['Jerusalem',['Matthew 21 to 28'],'Temple, trial, cross, empty tomb.'],
    ['Emmaus',['Luke 24:13-35'],'The risen Jesus walks with two disciples.'],
    ['Caesarea',['Acts 10:1','Acts 23:23'],'Roman capital of the province; Pilate’s residence.'],
    ['Joppa',['Acts 9:36','Acts 10:5'],'Peter raises Tabitha; the vision before Cornelius.'],
    ['Ptolemais',['Acts 21:7'],'Acre, on Paul’s route to Jerusalem.'],
  ],
  notes:[
    ['Three rulers, one land','When Herod died in 4 BC Rome split his kingdom: Archelaus took Judea and Samaria (deposed AD 6, replaced by governors), Antipas took Galilee and Perea (he executed John and tried Jesus), Philip took the north east. Travellers crossed borders constantly.'],
    ['Why go through Samaria?','Jews often avoided Samaria by crossing into Perea. John 4 says Jesus "had to" pass through it, which is the point of the story.'],
    ['The Decapolis','A league of ten Greek cities east of the Jordan and the lake. Gentile, pig keeping, Greek speaking. Jesus’ visits there are deliberate crossings of the boundary.'],
    ['Distances','Nazareth to Capernaum is about 30 km, a long day’s walk. Galilee to Jerusalem is 120 to 150 km, four or five days.'],
  ],
},
{
  id:'paul', title:'Paul’s Journeys', shelf:'atlas',
  subtitle:'Three missionary journeys and the voyage to Rome, AD 46 to 60',
  intro:'Antioch in Syria sent Paul out three times, each journey longer than the last: Cyprus and Galatia; then across to Macedonia and Greece; then a long stay at Ephesus and a farewell tour. Arrested in Jerusalem, he spent two years at Caesarea and sailed for Rome as a prisoner, shipwrecked on Malta on the way. Acts gives the route almost stop by stop.',
  view:{ center:[27.5,37.5], zoom:5.2 },
  books:['Acts','Galatians','1 Thessalonians','Philippians','1 Corinthians','Ephesians','Romans'],
  regions:[],
  labels:[['Macedonia',[22.4,41.3]],['Achaia',[22.2,38.4]],['Asia',[29.4,38.7]],['Galatia',[33.6,39.3]],['Cilicia',[35.0,37.3]],['Syria',[37.3,35.3]],['Pamphylia',[31.0,37.15]],['Lycia',[29.6,36.6]],['Bithynia',[30.5,40.6]],['Cyprus',[33.2,35.05]],['Crete',[25.0,35.25]],['Italy',[13.6,42.6]],['Sicily',[14.3,37.6]],['Illyricum',[18.0,43.6]],['Mediterranean Sea',[19.0,35.0]],['Aegean Sea',[25.2,38.6]]],
  routes:[
    { id:'j1', label:'First journey, AD 46 to 48 (Acts 13 to 14)', color:'#62b6c9', legs:[
      leg('Antioch to Cyprus',['Antioch','Seleucia','Salamis','Paphos'],['Acts 13:4-12']),
      leg('Into Galatia',['Paphos','Perga','Antioch in Pisidia','Iconium','Lystra','Derbe'],['Acts 13:13-52','Acts 14:1-20']),
      leg('Back the same way',['Derbe','Lystra','Iconium','Antioch in Pisidia','Perga','Attalia',[33.4,36.45],'Seleucia','Antioch'],['Acts 14:21-28'],{ dashed:true }),
    ]},
    { id:'j2', label:'Second journey, AD 49 to 52 (Acts 15:36 to 18:22)', color:'#d69282', legs:[
      leg('Overland to Troas',['Antioch','Tarsus','Derbe','Lystra','Iconium','Antioch in Pisidia','Troas'],['Acts 15:40-41','Acts 16:1-8']),
      leg('Into Macedonia',['Troas','Samothrace','Neapolis','Philippi','Amphipolis','Apollonia','Thessalonica','Berea'],['Acts 16:9-40','Acts 17:1-14']),
      leg('Athens and Corinth',['Berea','Athens','Corinth'],['Acts 17:15-34','Acts 18:1-17']),
      leg('Home by sea',['Cenchreae',[24.0,37.5],[26.4,37.6],'Ephesus',[27.2,37.5],[28.3,36.1],[33.0,34.4],'Caesarea','Jerusalem','Antioch'],['Acts 18:18-22'],{ dashed:true }),
    ]},
    { id:'j3', label:'Third journey, AD 53 to 57 (Acts 18:23 to 21:17)', color:'#d9a441', legs:[
      leg('To Ephesus for three years',['Antioch','Tarsus','Derbe','Iconium','Antioch in Pisidia','Laodicea','Ephesus'],['Acts 18:23','Acts 19:1-41','Acts 20:31']),
      leg('Macedonia and Greece again',['Ephesus','Troas','Philippi','Thessalonica','Berea','Corinth'],['Acts 20:1-3']),
      leg('The farewell voyage',['Corinth','Berea','Thessalonica','Philippi','Neapolis','Troas','Assos','Mitylene','Chios','Samos','Miletus','Cos','Rhodes','Patara',[33.2,34.3],'Tyre','Ptolemais','Caesarea','Jerusalem'],['Acts 20:3-38','Acts 21:1-17'],{ dashed:true }),
    ]},
    { id:'rome', label:'To Rome as a prisoner, AD 59 to 60 (Acts 27 to 28)', color:'#ece7dc', legs:[
      leg('Caesarea to Crete',['Caesarea','Sidon',[34.6,35.8],[32.6,35.7],[31.0,36.1],'Myra',[28.6,36.15],'Cnidus',[26.35,35.25],'Fair Havens'],['Acts 27:1-8']),
      leg('Storm and shipwreck',['Fair Havens','Cauda','Malta'],['Acts 27:9-44'],{ dashed:true }),
      leg('Malta to Rome',['Malta','Syracuse','Rhegium',[15.2,39.6],'Puteoli','Forum of Appius','Rome'],['Acts 28:1-16']),
    ]},
  ],
  places:[
    ['Antioch',['Acts 11:19-26','Acts 13:1-3'],'Home church that sent Paul out; where believers were first called Christians.'],
    ['Tarsus',['Acts 9:11','Acts 22:3'],'Paul’s birthplace in Cilicia.'],
    ['Salamis',['Acts 13:5'],'First preaching in the synagogues of Cyprus.'],
    ['Paphos',['Acts 13:6-12'],'Sergius Paulus believes; Elymas struck blind.'],
    ['Perga',['Acts 13:13'],'Where John Mark turned back.'],
    ['Antioch in Pisidia',['Acts 13:14-52'],'Paul’s first recorded sermon; driven out.'],
    ['Iconium',['Acts 14:1-7'],'Preaching and plots.'],
    ['Lystra',['Acts 14:8-20','Acts 16:1'],'A cripple healed; Paul stoned and left for dead; Timothy’s home.'],
    ['Derbe',['Acts 14:20-21'],'Eastern end of the first journey.'],
    ['Troas',['Acts 16:8-10','Acts 20:6-12'],'The vision of the man of Macedonia; Eutychus falls from the window.'],
    ['Philippi',['Acts 16:12-40','Philippians'],'Lydia; the jailer; the first church in Europe.'],
    ['Thessalonica',['Acts 17:1-9','1 Thessalonians'],'Three sabbaths, then riots.'],
    ['Berea',['Acts 17:10-14'],'They examined the Scriptures daily.'],
    ['Athens',['Acts 17:16-34'],'The Areopagus sermon.'],
    ['Corinth',['Acts 18:1-18','1 Corinthians'],'Eighteen months; Gallio; the church of the letters.'],
    ['Cenchreae',['Acts 18:18','Romans 16:1'],'Corinth’s eastern port; Phoebe’s church.'],
    ['Ephesus',['Acts 19','Ephesians','Revelation 2:1-7'],'Three years; the riot of the silversmiths; the great church of Asia.'],
    ['Miletus',['Acts 20:15-38'],'Farewell to the Ephesian elders.'],
    ['Tyre',['Acts 21:3-6'],'Disciples beg him not to go to Jerusalem.'],
    ['Caesarea',['Acts 21:8','Acts 23:33 to 26:32'],'Philip’s home; two years in Herod’s praetorium before Felix and Festus.'],
    ['Jerusalem',['Acts 21:17 to 23:22'],'Arrest in the temple.'],
    ['Myra',['Acts 27:5'],'Change of ship to an Alexandrian grain carrier.'],
    ['Fair Havens',['Acts 27:8'],'The harbour they should have wintered in.'],
    ['Malta',['Acts 28:1-10'],'Shipwreck; the viper; Publius’ father healed.'],
    ['Syracuse',['Acts 28:12'],'Three days in Sicily.'],
    ['Puteoli',['Acts 28:13'],'Landfall in Italy.'],
    ['Rome',['Acts 28:14-31','Romans'],'Two years under house arrest, preaching unhindered.'],
    ['Colossae',['Colossians'],'A church Paul never visited but wrote to.'],
  ],
  notes:[
    ['Where is Galatia?','Paul’s Galatians were either the cities of the first journey in the Roman province (the south Galatian view, the majority today) or ethnic Galatians further north. The map follows the southern view.'],
    ['Dates','Gallio was proconsul of Achaia in AD 51 to 52 (Acts 18:12), which anchors the whole chronology. Everything else is counted from that inscription at Delphi.'],
    ['A fourth journey?','Romans 15:24 and the Pastoral letters suggest Paul was released and travelled again, perhaps to Spain and Crete, before a second Roman imprisonment and death under Nero around AD 64 to 67. Acts ends before that.'],
    ['Letters on the road','Galatians during or after the first journey; 1 and 2 Thessalonians from Corinth on the second; 1 Corinthians from Ephesus, 2 Corinthians from Macedonia and Romans from Corinth on the third; Philippians, Colossians, Ephesians and Philemon from prison, most likely Rome.'],
  ],
},
{
  id:'seven-churches', title:'The Seven Churches of Revelation', shelf:'atlas',
  subtitle:'A postal circuit through Roman Asia, read from Patmos',
  intro:'John writes from exile on Patmos to seven churches on the mainland. The order of the letters is the order a courier would ride: north from Ephesus up the coast to Pergamum, then inland and south through the Hermus and Lycus valleys to Laodicea. Colossae and Hierapolis, a few miles from Laodicea, complete the picture.',
  view:{ center:[27.9,38.2], zoom:7.4 },
  books:['Revelation','Ephesians','Colossians'],
  regions:[],
  labels:[['Asia',[28.6,39.0]],['Aegean Sea',[26.0,38.2]],['Mysia',[27.8,39.6]],['Lydia',[28.3,38.6]],['Phrygia',[29.9,38.6]],['Caria',[28.0,37.4]]],
  routes:[
    { id:'circuit', label:'The courier’s circuit', color:'#d69282', legs:[
      leg('From Patmos to the coast',['Patmos','Ephesus'],['Revelation 1:9-11'],{ dashed:true }),
      leg('Up the coast',['Ephesus','Smyrna','Pergamum'],['Revelation 2:1-17']),
      leg('Inland and south',['Pergamum','Thyatira','Sardis','Philadelphia','Laodicea'],['Revelation 2:18 to 3:22']),
    ]},
  ],
  places:[
    ['Patmos',['Revelation 1:9'],'John’s exile "because of the word of God".'],
    ['Ephesus',['Revelation 2:1-7'],'Hard working and orthodox, but "you have abandoned the love you had at first."'],
    ['Smyrna',['Revelation 2:8-11'],'Poor and persecuted, yet rich. "Be faithful, even to the point of death."'],
    ['Pergamum',['Revelation 2:12-17'],'Where Satan has his throne; faithful under pressure, tolerating false teaching.'],
    ['Thyatira',['Revelation 2:18-29'],'Loving and growing, but tolerating "Jezebel". Lydia of Philippi came from here.'],
    ['Sardis',['Revelation 3:1-6'],'A reputation for being alive, but dead. "Wake up."'],
    ['Philadelphia',['Revelation 3:7-13'],'Little strength, an open door, no rebuke.'],
    ['Laodicea',['Revelation 3:14-22','Colossians 4:16'],'Neither hot nor cold. Wealthy, with lukewarm piped water; "I stand at the door and knock."'],
    ['Colossae',['Colossians 1:2','Colossians 4:13'],'Ten miles from Laodicea; Epaphras’ church.'],
    ['Hierapolis',['Colossians 4:13'],'Hot springs above the Lycus valley; the source of the lukewarm water image.'],
    ['Miletus',['Acts 20:17'],'Where Paul had said farewell to the Ephesian elders a generation earlier.'],
  ],
  notes:[
    ['Why these seven?','There were other churches in Asia, Colossae among them. Seven is completeness, and these seven sat on the main road so a single letter could circulate to all of them.'],
    ['Local colour in every letter','Smyrna’s crown of buildings, Pergamum’s temple to Rome, Sardis’s twice captured acropolis, Philadelphia’s earthquakes, Laodicea’s lukewarm aqueduct and eye salve. John knew these cities and wrote to what they knew.'],
    ['When?','Most scholars date Revelation to the end of Domitian’s reign, about AD 95. A minority place it under Nero in the late 60s.'],
  ],
},
];

// Which reference items belong on which chapters. type: 'atlas' | 'diagram' | 'chart'
export const REFLINKS = [
  { book:'Exodus', from:12, to:19, type:'atlas', id:'exodus', title:'The Exodus from Egypt' },
  { book:'Exodus', from:25, to:40, type:'diagram', id:'tabernacle', title:'The tabernacle' },
  { book:'Numbers', from:1, to:4, type:'diagram', id:'camp', title:'The camp of Israel' },
  { book:'Numbers', from:10, to:36, type:'atlas', id:'exodus', title:'The Exodus from Egypt' },
  { book:'Deuteronomy', from:1, to:34, type:'atlas', id:'exodus', title:'The Exodus from Egypt' },
  { book:'Joshua', from:1, to:24, type:'atlas', id:'tribes', title:'The Twelve Tribes' },
  { book:'Judges', from:1, to:21, type:'atlas', id:'tribes', title:'The Twelve Tribes' },
  { book:'1 Kings', from:5, to:8, type:'diagram', id:'solomon-temple', title:'Solomon’s temple' },
  { book:'1 Kings', from:12, to:22, type:'atlas', id:'divided-kingdom', title:'Israel and Judah' },
  { book:'1 Kings', from:12, to:22, type:'chart', id:'kings', title:'Kings and prophets' },
  { book:'2 Kings', from:1, to:25, type:'atlas', id:'divided-kingdom', title:'Israel and Judah' },
  { book:'2 Kings', from:1, to:25, type:'chart', id:'kings', title:'Kings and prophets' },
  { book:'2 Chronicles', from:1, to:7, type:'diagram', id:'solomon-temple', title:'Solomon’s temple' },
  { book:'2 Chronicles', from:10, to:36, type:'chart', id:'kings', title:'Kings and prophets' },
  { book:'Matthew', from:1, to:28, type:'atlas', id:'jesus', title:'The Land in the Days of Jesus' },
  { book:'Matthew', from:21, to:27, type:'diagram', id:'herod-temple', title:'Herod’s temple' },
  { book:'Mark', from:1, to:16, type:'atlas', id:'jesus', title:'The Land in the Days of Jesus' },
  { book:'Luke', from:1, to:24, type:'atlas', id:'jesus', title:'The Land in the Days of Jesus' },
  { book:'John', from:1, to:21, type:'atlas', id:'jesus', title:'The Land in the Days of Jesus' },
  { book:'Acts', from:13, to:28, type:'atlas', id:'paul', title:'Paul’s Journeys' },
  { book:'Revelation', from:1, to:3, type:'atlas', id:'seven-churches', title:'The Seven Churches' },
  { book:'Hebrews', from:8, to:10, type:'diagram', id:'tabernacle', title:'The tabernacle' },
];
export const mapById = id => MAPS.find(m => m.id === id);
// Validate that every place named in a map exists in the gazetteer (throws at import time if not).
for (const m of MAPS) { for (const r of m.routes) for (const l of r.legs) for (const s of l.stops) if (typeof s==='string') P(s); for (const p of m.places) P(p[0]); }
export { PLACES };
