import { art, sectionArt, chapterArt } from './artwork.js';
// Generated from the prototype, then adapted: HTML string renderers for Emmaus pages.
import * as D from './data.js';
import { P, ico, pattern, GICON, SICON } from './icons.js';
import { S } from './state.js';
import { REFLINKS } from './atlas/maps.js';
const { GENRES, BOOKS, slug, TOTAL, BLB, hubSlug, links, THESES, VIDS, MTV, MTQ, SECDESC, TITLES, RELATED, BEAT, LORDS, JOURNEY, KEYV, MT, COL, PEOPLE, ROLES, FULL, PTHEME, PARABLES, EVENTS, COMMANDS, PLACES, BEYOND, PATHS, SEED_DECK, RESOURCES } = D;
const byName=n=>BOOKS.find(b=>b.name===n);export const bySlug=s=>BOOKS.find(b=>b.slug===s);
export const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
const ext=()=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 4h6v6"></path><path d="M20 4l-9 9"></path><path d="M19 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h5"></path></svg>';

export const extLinks=(b,ch)=>`<div style="display:flex;gap:8px;flex-wrap:wrap">${links(b,ch).map(([n,u,d])=>`<a class="ext" href="${u}" target="_blank" rel="noopener" title="${esc(d)}">${n} ${ext()}</a>`).join('')}</div>`;
export function chips(tags){if(!tags)return'';const o=[];(tags.people||[]).forEach(p=>o.push(`<a class="chip person" href="/people/${slug(p)}">${ico('person',13)}${p}</a>`));(tags.parables||[]).forEach(p=>o.push(`<a class="chip parable" href="/parables">${ico('seed',13)}${p}</a>`));(tags.events||[]).forEach(p=>o.push(`<a class="chip event" href="/timeline">${ico('flag',13)}${p}</a>`));(tags.teachings||[]).forEach(p=>o.push(`<a class="chip teaching" href="/commandments">${ico('scroll',13)}${p}</a>`));(tags.places||[]).forEach(p=>o.push(`<a class="chip place" href="/places">${ico('pin',13)}${p}</a>`));return `<div style="display:flex;gap:6px;flex-wrap:wrap">${o.join('')}</div>`}
export const video=(id,t,d)=>`<div class="vid card"><a class="thumb" href="https://www.youtube.com/watch?v=${id}" target="_blank" rel="noopener" aria-label="Watch ${t} on YouTube"><img src="https://i.ytimg.com/vi/${id}/hqdefault.jpg" alt="" onerror="this.style.display='none'"><span class="playbtn">${ico('play',26)}</span></a><div style="padding:14px 16px"><div style="font-size:18px;font-weight:500">${t}</div><div class="note">${d} · BibleProject</div></div></div>`;
export function ribbon(hl,h=34){const W=1000;let x=0;const segs=BOOKS.map(b=>{const w=b.ch/TOTAL*W;const s=`<a href="/book/${b.slug}"><rect x="${x.toFixed(2)}" y="${hl&&b.slug===hl?0:6}" width="${Math.max(w-0.6,0.4).toFixed(2)}" height="${hl&&b.slug===hl?h:h-6}" fill="${b.col}" opacity="${hl?(b.slug===hl?1:.45):.9}"><title>${b.name} · ${b.ch} chapters</title></rect></a>`;x+=w;return s}).join('');const ot=BOOKS.filter(b=>b.t==='OT').reduce((a,b)=>a+b.ch,0)/TOTAL*W;
 return `<svg class="ribbon" viewBox="0 0 ${W} ${h+22}" preserveAspectRatio="none" style="height:${h+22}px" aria-label="The 66 books by length">${segs}<text x="0" y="${h+18}" fill="var(--dim)" style="font-family:'Instrument Sans',sans-serif;font-size:11px;letter-spacing:.08em">OLD TESTAMENT · ${Math.round(ot/W*100)}%</text><text x="${W}" y="${h+18}" text-anchor="end" fill="var(--dim)" style="font-family:'Instrument Sans',sans-serif;font-size:11px;letter-spacing:.08em">NEW TESTAMENT</text><line x1="${ot}" y1="0" x2="${ot}" y2="${h}" stroke="var(--bg)" stroke-width="3"/></svg>`}
export function mapSvg(highlight,journey){const k=200,lon0=34.4,lat0=33.7;const X=lon=>(lon-lon0)*k*.85,Y=lat=>(lat0-lat)*k;const coast=[[35.37,33.56],[35.20,33.27],[35.07,32.93],[34.99,32.82],[34.92,32.62],[34.89,32.50],[34.75,32.05],[34.55,31.67],[34.45,31.50],[34.30,31.30]];
 const land=`M${X(coast[0][0])} 0 `+coast.map(([lo,la])=>`L${X(lo).toFixed(1)} ${Y(la).toFixed(1)}`).join(' ')+` L${X(34.30)} 470 L330 470 L330 0 Z`;
 const pts=PLACES.map(([n,lo,la])=>{const hi=!highlight||highlight.includes(n);const right=lo<35.3;return `<a href="/places"><circle cx="${X(lo).toFixed(1)}" cy="${Y(la).toFixed(1)}" r="${hi?4.5:3}" fill="${hi?'var(--accent)':'var(--dim)'}"/><text x="${(X(lo)+(right?8:-8)).toFixed(1)}" y="${(Y(la)+4).toFixed(1)}" text-anchor="${right?'start':'end'}" fill="${hi?'var(--ink)':'var(--dim)'}" style="font-family:'Instrument Sans',sans-serif;font-size:11px">${n}</text></a>`}).join('');
 return `<svg viewBox="0 0 330 470" width="100%" style="display:block;max-height:560px" aria-label="Map of the Holy Land"><rect width="330" height="470" fill="var(--sea)"/><path d="${land}" fill="var(--land)"/><ellipse cx="${X(35.59)}" cy="${Y(32.82)}" rx="${(0.06*k*.85).toFixed(1)}" ry="${(0.11*k).toFixed(1)}" fill="var(--sea)"/><ellipse cx="${X(35.48)}" cy="${Y(31.5)}" rx="${(0.07*k*.85).toFixed(1)}" ry="${(0.32*k).toFixed(1)}" fill="var(--sea)"/><path d="M${X(35.57)} ${Y(32.71)} C${X(35.60)} ${Y(32.4)} ${X(35.50)} ${Y(32.1)} ${X(35.53)} ${Y(31.82)}" fill="none" stroke="var(--sea)" stroke-width="2.5"/><text x="14" y="${Y(32.6)}" fill="var(--dim)" style="font-family:'Instrument Sans',sans-serif;font-size:11px;letter-spacing:.14em" transform="rotate(-70 14 ${Y(32.6)})">MEDITERRANEAN</text><text x="${X(35.59)}" y="${Y(32.98)}" text-anchor="middle" fill="var(--dim)" style="font-family:'Instrument Sans',sans-serif;font-size:9px">Sea of Galilee</text><text x="${X(35.48)}" y="${Y(31.13)}" text-anchor="middle" fill="var(--dim)" style="font-family:'Instrument Sans',sans-serif;font-size:9px">Dead Sea</text>${pts}${journey?journeyPath():''}<line x1="230" y1="452" x2="${230+0.5*k*.85*0.5}" y2="452" stroke="var(--ink)"/><text x="230" y="446" fill="var(--dim)" style="font-family:'Instrument Sans',sans-serif;font-size:9px">50 km</text></svg>`}
export function timelineSvg(){const W=1000,h=150;const x=y=>10+((y+2100)/2200)*(W-20);const ticks=[-2000,-1500,-1000,-500,0];const ev=EVENTS.filter(e=>e[0]<0||e[0]===27);let up=true;
 const marks=ev.map((e,i)=>{const a=x(e[0]),b=x(e[1]);up=!up;const ty=up?38:118;return `<rect x="${a-2}" y="70" width="${Math.max(b-a,4)}" height="10" fill="var(--accent)" opacity="${b>a?.5:1}"/><line x1="${a}" y1="${up?48:80}" x2="${a}" y2="${up?70:108}" stroke="var(--line)"/><text x="${a}" y="${ty}" text-anchor="middle" fill="var(--ink)" style="font-family:'Instrument Sans',sans-serif;font-size:11px">${e[3].length>22?e[3].slice(0,21)+'…':e[3]}</text><text x="${a}" y="${ty+13}" text-anchor="middle" fill="var(--dim)" style="font-family:'Instrument Sans',sans-serif;font-size:10px">${e[2]}</text>`}).join('');
 return `<svg viewBox="0 0 ${W} ${h}" width="100%" style="display:block" aria-label="Timeline from Abraham to Jesus"><line x1="10" y1="75" x2="${W-10}" y2="75" stroke="var(--line)"/>${ticks.map(t=>`<line x1="${x(t)}" y1="71" x2="${x(t)}" y2="79" stroke="var(--dim)"/><text x="${x(t)}" y="${h-4}" text-anchor="middle" fill="var(--dim)" style="font-family:'Instrument Sans',sans-serif;font-size:10px;letter-spacing:.06em">${t<0?-t+' BC':'AD 1'}</text>`).join('')}${marks}</svg>`}
export function centurySvg(){const W=1000,h=140;const x=y=>10+((y+10)/110)*(W-20);const ev=EVENTS.filter(e=>e[0]>=-10&&e[0]!==27||e[3]==='Public ministry of Jesus');let up=false;
 const marks=ev.map(e=>{const a=x(e[0]),b=x(e[1]);up=!up;const ty=up?34:112;return `<rect x="${a-2}" y="66" width="${Math.max(b-a,4)}" height="10" fill="#4d6f95" opacity="${b>a?.55:1}"/><line x1="${a}" y1="${up?44:76}" x2="${a}" y2="${up?66:102}" stroke="var(--line)"/><text x="${a}" y="${ty}" text-anchor="middle" fill="var(--ink)" style="font-family:'Instrument Sans',sans-serif;font-size:11px">${e[3].length>26?e[3].slice(0,25)+'…':e[3]}</text><text x="${a}" y="${ty+13}" text-anchor="middle" fill="var(--dim)" style="font-family:'Instrument Sans',sans-serif;font-size:10px">${e[2]}</text>`}).join('');
 return `<svg viewBox="0 0 ${W} ${h}" width="100%" style="display:block" aria-label="The first century"><line x1="10" y1="71" x2="${W-10}" y2="71" stroke="var(--line)"/>${[0,25,50,75,100].map(t=>`<line x1="${x(t)}" y1="67" x2="${x(t)}" y2="75" stroke="var(--dim)"/><text x="${x(t)}" y="${h-2}" text-anchor="middle" fill="var(--dim)" style="font-family:'Instrument Sans',sans-serif;font-size:10px;letter-spacing:.06em">${t===0?'AD 1':'AD '+t}</text>`).join('')}${marks}</svg>`}
export function scene(){const rays=Array.from({length:16},(_,i)=>{const a=i*Math.PI/8;const x1=300+Math.cos(a)*74,y1=132+Math.sin(a)*74,x2=300+Math.cos(a)*(i%2?86:96),y2=132+Math.sin(a)*(i%2?86:96);return `<line x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}"/>`}).join('');
 return `<svg class="scene" viewBox="0 0 600 340" aria-label="A road toward a rising sun"><defs><linearGradient id="sky" x1="0" y1="0" x2="0" y2="1"><stop offset="0" style="stop-color:var(--card)"/><stop offset="1" style="stop-color:var(--accent-soft)"/></linearGradient><linearGradient id="road" x1="0" y1="0" x2="0" y2="1"><stop offset="0" style="stop-color:var(--line)"/><stop offset="1" style="stop-color:var(--card)"/></linearGradient></defs>
 <rect width="600" height="340" fill="url(#sky)"/>
 <g fill="var(--ink)">${[[40,30],[92,64],[150,22],[210,58],[262,18],[338,40],[402,26],[452,70],[512,34],[560,60],[586,18],[122,98],[478,104],[28,120],[372,92]].map(([x,y],i)=>`<circle class="tw" cx="${x}" cy="${y}" r="${i%3?1.1:1.7}" style="animation-delay:${(i*.37)%3}s"/>`).join('')}</g>
 <g class="rays" stroke="var(--accent)" stroke-width="1.5" stroke-linecap="round" opacity=".55">${rays}</g>
 <g class="sunrise"><circle cx="300" cy="132" r="56" fill="var(--accent-soft)" stroke="var(--accent)" stroke-width="2"/><circle cx="300" cy="132" r="40" fill="none" stroke="var(--accent)" stroke-width="1" opacity=".35"/></g>
 <path d="M0 232c70-26 130-40 200-36s120 28 200 24 140-26 200-40v160H0z" fill="var(--land)"/>
 <path d="M0 262c90-20 160-30 240-22s150 26 220 18 100-20 140-30v112H0z" fill="var(--narr)" opacity=".7"/>
 <path d="M0 340V292c60-14 150-24 260-18l32 0 32 0c110-6 200 4 276 18v48z" fill="var(--land)"/>
 <path d="M228 340L292 216h16l64 124z" fill="url(#road)" stroke="var(--line)" stroke-width="1.5"/>
 <path d="M300 236v14M300 262v18M300 294v24" stroke="var(--dim)" stroke-width="2" stroke-linecap="round" opacity=".6"/>
 <path d="M0 216h228M372 216h228" stroke="var(--accent)" stroke-width="1" opacity=".4"/>
 <g stroke="var(--dim)" stroke-width="1.5" fill="none" stroke-linecap="round"><path d="M108 96l6-4 6 4M126 108l5-3 5 3"/><path d="M470 84l6-4 6 4"/></g>
 <g stroke="var(--ink)" stroke-width="2" stroke-linecap="round" fill="none" opacity=".8"><path d="M284 232v-16M284 216l-5 8M284 216l5 6"/><path d="M296 236v-18M296 218l-5 9M296 218l6 7"/><circle cx="284" cy="212" r="2.4" fill="var(--ink)"/><circle cx="296" cy="214" r="2.4" fill="var(--ink)"/><path d="M284 222l-4 6M284 222l4 5M296 224l-4 7M296 224l4 6"/></g>
 <text x="24" y="318" fill="var(--dim)" style="font-family:'Instrument Sans',sans-serif;font-size:11px;letter-spacing:.14em">THE ROAD TO EMMAUS · LUKE 24</text></svg>`}
export const mins=v=>{const m=Math.round(v*7.8/60);return m<1?'under a minute':m+' min'};
export function journeyPath(){const k=200,lon0=34.4,lat0=33.7;const X=lon=>(lon-lon0)*k*.85,Y=lat=>(lat0-lat)*k;const pts=JOURNEY.map(([n])=>PLACES.find(p=>p[0]===n));const d=pts.map((p,i)=>`${i?'L':'M'}${X(p[1]).toFixed(1)} ${Y(p[2]).toFixed(1)}`).join(' ');return `<path d="${d}" fill="none" stroke="var(--accent)" stroke-width="1.5" stroke-dasharray="4 4" opacity=".8"/>`+pts.map((p,i)=>`<g><circle cx="${X(p[1]).toFixed(1)}" cy="${Y(p[2]).toFixed(1)}" r="8" fill="var(--accent)"/><text x="${X(p[1]).toFixed(1)}" y="${(Y(p[2])+3.5).toFixed(1)}" text-anchor="middle" fill="var(--bg)" style="font-family:'Instrument Sans',sans-serif;font-size:9px;font-weight:600">${i+1}</text></g>`).join('')}
export const sect=(label,body,sub='',icon='')=>`<div class="sect"><div><div class="lab si" style="color:var(--ink)">${icon?`<span class="gi">${ico(icon,16)}</span>`:''}<span>${label}</span></div>${sub?`<div class="note" style="margin-top:8px;line-height:1.5">${sub}</div>`:''}${sectionArt[label]?art(sectionArt[label],'art-margin'):''}</div><div>${body}</div></div>`;
export function verseCard(ref,text){const inDeck=S.DECKS.some(d=>d.cards.some(c=>c[0]===ref));return `<div class="verse"><span class="ref">${ref}</span><span style="font-size:18px;line-height:1.5">${esc(text)}</span><div><button class="btn ghost sm addv" data-ref="${esc(ref)}" data-txt="${esc(text)}" ${inDeck?'disabled':''}>${inDeck?ico('check',14)+' In your deck':ico('plus',14)+' Memorise this'}</button></div>${art('D1','art-corner')}</div>`}

/* ================= VIEWS ================= */
export function home(){const lb=bySlug(S.LAST.book)||bySlug('matthew');const lt=S.LAST.book==='matthew'?MT.ch[S.LAST.ch-1][1]:'';
 return `<div class="wrap">
 <div class="hero">
  <div><div class="lab" style="display:flex;gap:10px;align-items:center">${art('logo','art-home-mark')}The whole Bible, opened as one story</div>
   <h1 class="h1" style="margin-top:14px" aria-label="Emmaus">${art('wordmark','art-home-wordmark')}</h1>
   <p style="font-size:24px;line-height:1.4;margin:22px 0 0;max-width:600px;font-style:italic">“Did not our hearts burn within us while He talked with us on the road and opened the Scriptures to us?”</p><div class="note" style="margin-top:6px">Luke 24:32</div>
   <p style="font-size:19px;color:var(--dim);margin:22px 0 0;max-width:600px">66 books, ${TOTAL.toLocaleString()} chapters, written over about 1,500 years by some forty authors. Every book explained, every chapter summarised, every person and place linked, and the best of what already exists brought into one place.</p>
   <div style="display:flex;gap:10px;margin-top:26px;flex-wrap:wrap"><a class="btn" href="/book/matthew">${ico('fish',16)} Open Matthew</a><a class="btn ghost" href="/explore">${ico('compass',16)} Explore</a><a class="btn ghost" href="#" id="random">${ico('spark',16)} Open a random chapter</a></div></div>
  <div>${scene()}</div>
 </div>
 <div style="margin-top:40px">${ribbon(null,40)}</div>
 <div class="strip" style="margin-top:14px">${GENRES.map(g=>`<a href="/book/${byName(g.books[0][0]).slug}" class="gl" title="${g.name}"><span class="gi" style="color:${g.col}">${ico(GICON[g.id],18)}</span><span>${g.name}</span><span class="note" style="font-size:12px">${g.books.length}</span></a>`).join('')}</div>
 <div class="grid2" style="margin-top:36px;align-items:stretch">
  <div class="card" style="padding:22px 26px;display:flex;justify-content:space-between;align-items:center;gap:20px;flex-wrap:wrap">
   <div style="display:flex;gap:18px;align-items:center"><span class="gi big" style="color:${lb.col}">${ico(GICON[lb.gid],30)}</span><div><div class="lab" style="color:var(--accent)">Last opened</div><div style="font-size:24px;font-weight:500;line-height:1.15;margin-top:4px">${lb.name} ${S.LAST.ch}${lt?' · '+lt:''}</div></div></div>
   <a class="btn" href="/book/${lb.slug}/${S.LAST.ch}">Open</a></div>
  <a class="card" href="/book/matthew" style="padding:22px 26px;display:flex;gap:18px;align-items:center;color:var(--ink)"><span class="gi big" style="color:#4d6f95">${ico('fish',30)}</span><div><div class="lab" style="color:var(--accent)">Finished overview</div><div style="font-size:24px;font-weight:500;line-height:1.15;margin-top:4px">Matthew, all 28 chapters</div><div class="note" style="margin-top:2px">The template every other book will follow</div></div></a>
 </div>
 ${sect('Paths through the Bible',`<div class="grid2">${PATHS.map(([t,d,i,bks])=>`<div class="path"><span class="gi">${ico(i,22)}</span><span><span style="font-size:20px;font-weight:500;line-height:1.2;display:block">${t}</span><span class="note">${d}</span><span class="bks">${bks.map((b,j)=>`<a href="/book/${slug(b)}"><span>${j+1}. ${b}</span></a>`).join('')}</span></span></div>`).join('')}</div>`,'Curated orders, not plans. Nothing is tracked; pick one and read.','road')}
 ${Object.keys(S.NOTES).length?sect('Your notes',`<div class="grid3">${Object.entries(S.NOTES).filter(([k,v])=>v.trim()).slice(-3).reverse().map(([k,v])=>{const [bs,ch]=k.split(':');const b=bySlug(bs);return `<a class="card" href="/book/${bs}/${ch}" style="padding:16px 18px;color:var(--ink)"><div class="lab" style="color:var(--accent)">${b?b.name:bs} ${ch}</div><div style="margin-top:6px;font-size:16px;color:var(--dim);display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden">${esc(v)}</div></a>`}).join('')}</div><div style="margin-top:12px"><a href="/notes">All notes →</a></div>`,'','pen'):''}
 ${art('D2','art-divider')}
 ${GENRES.map(g=>`<div class="sect"><div>${g.id==='law'?art('A1','art-book'):''}<span class="gi" style="color:${g.col}">${ico(GICON[g.id],26)}</span><div class="lab" style="color:var(--ink);margin-top:12px">${g.name}</div><div class="note" style="margin-top:6px">${g.t==='OT'?'Old':'New'} Testament · ${g.books.length} books · ${g.books.reduce((a,b)=>a+b[1],0)} chapters</div></div>
  <div class="books">${g.books.map(([n,c])=>{const b=byName(n);return `<a class="book ${b.slug==='matthew'?'ready':''}" href="/book/${b.slug}" title="${esc(THESES[n]||'')}" style="--gc:${g.col}"><div class="top"><div class="n">${n}</div>${ico(GICON[g.id],14)}</div><div class="c">${c} chapter${c>1?'s':''}</div></a>`}).join('')}</div></div>`).join('')}
 <p class="note" style="margin-top:40px">Books with a coloured edge have a finished overview. In the prototype that is Matthew. Every other book opens the same skeleton with working resource links and the written content marked as not yet written.</p>
 </div>`}

export function book(s){const b=bySlug(s);if(!b)return notFound();const isMt=s==='matthew';const prev=BOOKS[b.idx-2],next=BOOKS[b.idx];
 const structure=isMt?`<div style="display:flex;gap:2px;height:36px">${MT.ch.map(c=>`<a href="/book/matthew/${c[0]}" title="Chapter ${c[0]}: ${c[1]}" style="flex:1;background:${COL[c[2]]};display:flex;align-items:flex-end;justify-content:center;padding-bottom:4px"><span class="tag" style="color:${c[2]==='disc'?'#fff':c[2]==='pass'?'var(--pass-ink)':'var(--ink)'};font-size:10px">${c[0]}</span></a>`).join('')}</div>
 <div style="display:flex;gap:2px;margin-top:8px">${MT.sections.map(([n,a,z])=>`<div class="tag" style="flex:${z-a+1};border-top:1px solid var(--line);padding-top:6px;min-width:0;font-size:11px;line-height:1.3">${n}</div>`).join('')}</div>
 <div class="grid3" style="margin-top:22px;gap:10px">${MT.sections.map(([n,a,z,t])=>`<a href="/book/matthew/${a}" class="card" style="padding:12px 14px;display:flex;gap:12px;align-items:center;color:var(--ink)"><span class="sq" style="background:${COL[t]};color:${t==='disc'?'#fff':t==='pass'?'var(--pass-ink)':'var(--ink)'}">${ico(SICON[t],16)}</span><span><span style="font-weight:500;display:block;line-height:1.2">${n} <span class="note">${a===z?a:a+' to '+z}</span></span><span class="note">${SECDESC[n]}</span></span></a>`).join('')}</div>
 <div class="tag" style="display:flex;gap:18px;margin-top:12px;flex-wrap:wrap"><span style="display:inline-flex;gap:6px;align-items:center"><span class="dot" style="background:var(--accent)"></span>Five teaching blocks</span><span style="display:inline-flex;gap:6px;align-items:center"><span class="dot" style="background:var(--narr)"></span>Narrative</span><span style="display:inline-flex;gap:6px;align-items:center"><span class="dot" style="background:var(--pass)"></span>Passion and resurrection</span></div>
 <p style="color:var(--dim);font-size:16px;margin:16px 0 0;max-width:680px">Narrative and teaching alternate. Twice Matthew writes "from that time Jesus began", at 4:17 and 16:21, marking the turn to public ministry and the turn toward the cross.</p>`:`<div class="stub">Structure map: not yet written for ${b.name}. It will show the book’s movements across ${b.ch} chapters, like Matthew’s.</div>`;
 const rows=Array.from({length:b.ch},(_,i)=>{const n=i+1;const c=isMt?MT.ch[i]:null;const sec=isMt?MT.sections.find(x=>x[1]===n):null;
  return (sec?`<div class="secrow"><span class="sq" style="background:${COL[sec[3]]};color:${sec[3]==='disc'?'#fff':sec[3]==='pass'?'var(--pass-ink)':'var(--ink)'}">${ico(SICON[sec[3]],18)}</span><span class="disp">${sec[0]}</span><span class="note">${sec[1]===sec[2]?'Chapter '+sec[1]:'Chapters '+sec[1]+' to '+sec[2]} · ${SECDESC[sec[0]]}</span><span class="line"></span></div>`:'')+`<div class="row" id="ch${n}"><div class="num"><span class="sq" style="background:${c?COL[c[2]]:'var(--line2)'};color:${c?(c[2]==='disc'?'#fff':c[2]==='pass'?'var(--pass-ink)':'var(--ink)'):'var(--dim)'}">${ico(c?SICON[c[2]]:'book',18)}</span><b>${n}</b></div>
  <div>${c?`<a class="t" href="/book/${s}/${n}">${c[1]}</a><p>${c[3]}</p><div class="more">${chips(c[5])}${extLinks(b,n)}</div><button class="toggle" data-t="${n}">Show people, parables and resources</button>`:`<a class="t" href="/book/${s}/${n}">Chapter ${n}</a><p class="note" style="margin-top:6px">Summary not yet written.</p><div class="more">${extLinks(b,n)}</div><button class="toggle" data-t="${n}">Show resources</button>`}</div>
  <div class="kv">${c?`Key verse <a href="/book/${s}/${n}">${c[4]}</a><br>${MTV[i]} verses · ${mins(MTV[i])}`:''}</div></div>`}).join('');
 return `<div class="wrap">
 <div class="crumb"><a href="/">Canon</a><span>/</span><a href="/">${b.genre}</a><span>/</span><span style="color:var(--ink)">${b.name}</span></div>
 <div class="poster" style="margin-top:28px;background-image:${pattern(GICON[b.gid],b.col)},linear-gradient(120deg,color-mix(in srgb,${b.col} 30%,var(--bg)) 0%,var(--bg) 62%)"><span class="wmk" style="color:${b.col}">${ico(GICON[b.gid],360)}</span><div><div class="lab" style="color:${b.col}">${b.gid==='gos'&&b.name!=='Acts'?'The Gospel according to':'The book of'}</div><h1 class="h1" style="margin-top:8px">${b.name}</h1>
  <div style="display:flex;gap:22px;align-items:baseline;margin-top:14px;flex-wrap:wrap"><span class="note">${b.ch} chapters${isMt?` · ${MT.date}`:''} · ${b.genre} · Book ${b.idx} of 66</span></div></div><span class="gi poster-ico" style="color:${b.col}">${ico(GICON[b.gid],72)}</span></div>
 <div style="margin-top:18px">${ribbon(s,22)}</div>
 <div style="display:flex;justify-content:space-between;font-size:15px;margin-top:6px;flex-wrap:wrap;gap:10px"><span>${prev?`<a href="/book/${prev.slug}">← ${prev.name}</a>`:''}</span><span class="note">Where ${b.name} sits in the canon</span><span>${next?`<a href="/book/${next.slug}">${next.name} →</a>`:''}</span></div>
 <p style="font-size:28px;line-height:1.35;margin:36px 0 0;max-width:820px;font-style:italic">${THESES[b.name]||MT.thesis}</p>
 ${isMt?`<div class="cal" style="margin-top:18px"><span>${MT.verses.toLocaleString()} verses</span><span>About 2 hours 20 minutes to read aloud</span><span>5 teaching blocks</span><span>${PARABLES.filter(p=>p[1].includes('Matthew')).length} parables</span><span>${MT.fulfil.length} fulfilment quotations</span></div>`:''}
 ${sect('Why this book matters',(isMt?`<div class="grid2" style="gap:28px 40px">${MT.why.map(([t,d])=>`<div><div style="font-size:22px;font-weight:500;line-height:1.2">${t}</div><p style="margin:8px 0 0;color:var(--dim);font-size:17px">${d}</p></div>`).join('')}</div>`:`<div class="stub">Four reasons this book matters: not yet written.</div>`),'','spark')}
 ${sect('Context',(isMt?`<div class="grid2">${MT.ctx.map(([k,v,d])=>`<div class="card" style="padding:20px 22px"><div class="lab">${k}</div><div style="font-size:21px;font-weight:500;line-height:1.2;margin-top:6px">${v}</div><p style="margin:10px 0 0;color:var(--dim);font-size:16px;line-height:1.5">${d}</p></div>`).join('')}</div>`:`<div class="grid2">${['Who wrote it','When','For whom','Where from','Why','Built from'].map(k=>`<div class="card" style="padding:20px 22px"><div class="lab">${k}</div><div class="note" style="margin-top:10px">Not yet written</div></div>`).join('')}</div>`),'','scroll')}
 ${isMt?sect('Themes',`<div class="grid3">${MT.themes.map(([t,i,d])=>`<div class="card" style="padding:18px 20px;display:flex;gap:14px"><span class="gi">${ico(i,22)}</span><div><div style="font-size:19px;font-weight:500;line-height:1.2">${t}</div><div style="color:var(--dim);font-size:15px;margin-top:4px">${d}</div></div></div>`).join('')}</div>`,'','layers'):''}
 ${isMt?sect('Who Jesus is in Matthew',`<div class="grid3">${TITLES.map(([t,d,r])=>`<div class="card" style="padding:18px 20px"><div class="disp" style="font-size:26px;line-height:1">${t}</div><div style="color:var(--dim);font-size:15px;margin-top:8px">${d}</div><div class="note" style="margin-top:8px;color:var(--accent)">${r}</div></div>`).join('')}</div>`,'The names and titles the book gives him, and where each one lands.','crown'):''}
 ${sect('Shape of the book',structure,'','mountain')}
 ${isMt?sect('Books Matthew leans on',`<div class="grid3">${RELATED.map(([n,d])=>{const rb=byName(n);return `<a class="card" href="/book/${rb.slug}" style="padding:14px 16px;display:flex;gap:12px;align-items:flex-start;color:var(--ink)"><span class="gi" style="color:${rb.col}">${ico(GICON[rb.gid],18)}</span><span><span style="font-weight:500;display:block">${n}</span><span class="note">${d}</span></span></a>`}).join('')}</div>`,'Two Gospels it shares material with, and the Old Testament books it quotes most.','link'):''}
 ${isMt?sect('Key verses',`<div class="grid2">${['1:21','4:17','5:17','16:16','16:24','20:28'].map(r=>verseCard('Matthew '+r,KEYV[r])).join('')}</div>`,'Six verses that carry the book. One click sends any of them to your memory deck.','quote'):''}
 ${isMt?sect('How Matthew reads the Old Testament',`<div class="tablewrap"><table><thead><tr><th>Matthew</th><th>Quoting</th><th>What is fulfilled</th></tr></thead><tbody>${MT.fulfil.map(([m,o,d])=>`<tr><td><a href="/book/matthew/${m.split(':')[0]}">${m}</a></td><td>${o}</td><td style="color:var(--dim)">${d}</td></tr>`).join('')}</tbody></table></div>`,'The twelve "fulfilment formula" quotations. Matthew introduces each with "this took place to fulfil what was spoken through the prophet".','link'):''}
 ${isMt?sect('Where traditions differ',`<div style="display:flex;flex-direction:column;gap:14px">${MT.trad.map(([t,d])=>`<div style="display:grid;grid-template-columns:200px minmax(0,1fr);gap:20px"><span style="font-weight:500">${t}</span><span style="color:var(--dim);font-size:16px">${d}</span></div>`).join('')}</div>`,'Stated, not settled. You decide.','scales'):''}
 ${sect('Watch the overview',(VIDS[s]?`<div class="grid2">${VIDS[s].map(([id,t,d])=>video(id,t,d)).join('')}</div>`:`<div class="stub">BibleProject overview video for ${b.name}: mapped from their Old and New Testament playlists in the real build.</div>`)+`<p class="note" style="margin-top:10px">Videos by <a href="https://bibleproject.com" target="_blank" rel="noopener">BibleProject</a>, embedded under their terms with credit.</p>`,'','play')}
 ${sect('Resources',`<div class="note" style="margin-bottom:10px">Everything that already exists for this book, in one place.</div>${extLinks(b,1)}`,'','shelf')}
 ${sect('Chapter by chapter',rows,'One or two sentences per chapter. Open a chapter for the text, people, parables, resources and your notes.','book')}
 </div>`}

export function chapter(s,n){const b=bySlug(s);n=+n;if(!b||n<1||n>b.ch)return notFound();const c=s==='matthew'?MT.ch[n-1]:null;const note=S.NOTES[s+':'+n]||'';S.LAST={book:s,ch:n};S.save();
 const sec=c?MT.sections.find(x=>n>=x[1]&&n<=x[2]):null;const prev=n>1?`<a href="/book/${s}/${n-1}">← ${b.name} ${n-1}${s==='matthew'?' · '+MT.ch[n-2][1]:''}</a>`:'';const nxt=n<b.ch?`<a href="/book/${s}/${n+1}">${b.name} ${n+1}${s==='matthew'?' · '+MT.ch[n][1]:''} →</a>`:'';
 const kv=c?KEYV[c[4]]:null;const verses=c?Object.keys(KEYV).filter(k=>+k.split(':')[0]===n):[];
 return `<div class="wrap">${chapterArt(s,n)?art(chapterArt(s,n),'art-chapter'):''}
 <div class="crumb"><a href="/">Canon</a><span>/</span><a href="/book/${s}">${b.name}</a><span>/</span><span style="color:var(--ink)">Chapter ${n}</span></div>
 <div style="display:flex;gap:18px;align-items:center;margin-top:36px"><span class="sq lg" style="background:${c?COL[c[2]]:'var(--line2)'};color:${c?(c[2]==='disc'?'#fff':c[2]==='pass'?'var(--pass-ink)':'var(--ink)'):'var(--dim)'}">${ico(c?SICON[c[2]]:'book',30)}</span><div><div class="lab">${b.name} · chapter ${n} of ${b.ch}${sec?' · '+sec[0]:''}${c?` · ${MTV[n-1]} verses · ${mins(MTV[n-1])}`:''}</div><h1 class="h1" style="font-size:clamp(40px,6vw,80px);margin-top:6px">${c?c[1]:'Chapter '+n}</h1>${sec?`<div class="note" style="margin-top:6px">${SECDESC[sec[0]]}</div>`:''}</div></div>
 ${c?`<div style="display:flex;gap:2px;height:8px;margin-top:22px;max-width:760px">${MT.ch.map(x=>`<a href="/book/matthew/${x[0]}" title="${x[0]} ${x[1]}" style="flex:1;background:${x[0]===n?'var(--ink)':COL[x[2]]};opacity:${x[0]===n?1:.55}"></a>`).join('')}</div>`:''}
 ${c?`<p style="font-size:22px;margin:22px 0 0;max-width:760px">${c[3]}</p>`:`<div class="stub" style="margin-top:22px">Chapter summary for ${b.name} ${n}: not yet written.</div>`}
 ${c?`<div class="grid2" style="margin-top:24px">${n>1?`<a class="card" href="/book/matthew/${n-1}" style="padding:14px 16px;color:var(--ink)"><div class="lab">Before · chapter ${n-1}</div><div style="font-weight:500;margin-top:4px">${MT.ch[n-2][1]}</div><div class="note" style="margin-top:4px">${MT.ch[n-2][3]}</div></a>`:'<div></div>'}${n<28?`<a class="card" href="/book/matthew/${n+1}" style="padding:14px 16px;color:var(--ink)"><div class="lab">After · chapter ${n+1}</div><div style="font-weight:500;margin-top:4px">${MT.ch[n][1]}</div><div class="note" style="margin-top:4px">${MT.ch[n][3]}</div></a>`:''}</div>`:''}
 ${c?sect('Key verse',kv?verseCard(`${b.name} ${c[4]}`,kv):`<div class="verse"><span class="ref">${b.name} ${c[4]}</span><span class="note">NLT text loads from Tyndale’s API in the real build.</span></div>`,'','quote'):''}
 ${sect('Read the text',`<div id="nlt-mount" data-ref="${esc(b.name+' '+n)}" data-book="${b.name}" data-ch="${n}"></div>`,'','book')}
 ${c?sect('Sit with this',`<div class="card" style="padding:22px 24px;display:flex;gap:16px;align-items:flex-start"><span class="gi">${ico('heart',20)}</span><div><p style="font-size:22px;line-height:1.4;margin:0;font-style:italic">${MTQ[n-1]}</p><div class="note" style="margin-top:10px">One question per chapter. Write your answer in the notes below, or take it to the tutor.</div></div></div>`,'','heart'):''}
 ${(()=>{const R=REFLINKS.filter(r=>r.book===b.name&&n>=r.from&&n<=r.to);if(!R.length)return'';const seen=new Set();const items=R.filter(r=>{const k=r.type+r.id;if(seen.has(k))return false;seen.add(k);return true});return sect('Reference',`<div class="grid3">${items.map(r=>`<a class="card" href="/reference/${r.type==='atlas'?'atlas':r.type==='diagram'?'diagrams':'charts'}/${r.id}" style="padding:16px 18px;color:var(--ink);display:flex;gap:12px;align-items:center"><span class="gi">${ico(r.type==='atlas'?'map':r.type==='diagram'?'tablets':'layers',20)}</span><span><span class="lab">${r.type}</span><span style="display:block;font-size:19px;font-weight:500;line-height:1.2">${r.title}</span></span></a>`).join('')}</div>`,'Maps, layouts and charts that explain this chapter.','map')})()}
 ${c&&c[5]?sect('In this chapter',chips(c[5])+`<p class="note" style="margin-top:12px">Every person, parable, event and place is a page of its own, with every chapter it appears in.</p>`,'','compass'):''}
 ${sect('Go deeper',extLinks(b,n)+`<p class="note" style="margin-top:12px">Opens the same chapter on each site. Nothing here is rebuilt; it is linked.</p>`,'','shelf')}
 ${sect('Your notes',`<textarea id="note" placeholder="What stood out, what you did not understand, what you want to come back to">${esc(note)}</textarea><div style="display:flex;gap:10px;align-items:center;margin-top:10px"><button class="btn ghost" id="savenote">Save note</button><span class="note" id="notestat"></span></div>`,'','pen')}
 ${sect('Ask the tutor',`<div style="display:flex;gap:10px"><input type="text" id="askq" placeholder="Ask about ${b.name} ${n}"><a class="btn" href="/tutor" id="askgo">Ask</a></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px">${(c?[`What is the main point of ${b.name} ${n}?`,'Quiz me on this chapter',c[5]&&c[5].parables?`What does the parable of ${c[5].parables[0].toLowerCase()} mean?`:'How does this chapter fit the whole book?']:[`What is ${b.name} about?`]).map(q=>`<a class="chip" href="/tutor?q=${encodeURIComponent(q)}">${ico('spark',12)}${q}</a>`).join('')}</div>`,'','spark')}
 <div style="display:flex;justify-content:space-between;margin-top:56px;font-size:16px;flex-wrap:wrap;gap:12px"><span>${prev}</span><span>${nxt}</span></div>
 </div>`}

export function explore(){const K=[['People','people',PEOPLE.length+' people in '+ROLES.length+' groups','Who they were, where they appear, what they were for.','person'],['Parables of Jesus','parables',PARABLES.length+' parables','Every parable, where it is told, and what it teaches.','seed'],['Places','places',PLACES.length+' places mapped','Real coordinates from open data; every place linked to its chapters.','map'],['Major events','timeline',EVENTS.length+' events','From Abraham to Revelation on one timeline.','flag'],['Commandments','commandments','3 sets','The Ten, the two greatest, and the commands of Jesus.','tablets'],['Teachings','commandments','Beatitudes, Lord’s Prayer, discourses','The Beatitudes and the Lord’s Prayer as flashcards, plus the great discourses.','mountain'],['Reference','reference','Atlas, diagrams, charts','Maps on real terrain, the tabernacle and temples to the cubit, kings and prophets on one timeline.','map']];
 return `<div class="wrap">${art('A2','art-page-heading')}<div class="lab">Unlock the book</div><h1 class="h1" style="margin-top:8px;font-size:clamp(48px,7vw,96px)">Explore</h1><p style="font-size:22px;color:var(--dim);margin:14px 0 0;max-width:720px">Everything in the Bible that is not a book or a chapter: the people, the stories Jesus told, the commands, the events and the places. Each one links to every chapter it appears in.</p>
 <div class="grid3" style="margin-top:40px">${K.map(([t,h,c,d,i])=>`<a class="card art-card" href="/${h}" style="padding:22px 24px;color:var(--ink);display:flex;flex-direction:column;gap:10px;min-height:190px">${art(({people:'C5',parables:'B4',places:'C3',timeline:'C4',commandments:'D3',reference:'C1'})[h],'art-card-heading')}<span class="gi">${ico(i,26)}</span><span class="lab">${c}</span><span style="font-size:26px;font-weight:500;line-height:1.15">${t}</span><span style="color:var(--dim);font-size:16px">${d}</span></a>`).join('')}</div></div>`}

export function people(){const RI={Patriarchs:'tablets',Leaders:'road',Kings:'crown',Prophets:'flame',Women:'heart',Apostles:'fish',Rulers:'scales','Early church':'lamp'};return `<div class="wrap">${art('C5','art-page-heading')}<div class="crumb"><a href="/explore">Explore</a><span>/</span><span style="color:var(--ink)">People</span></div><h1 class="h1" style="margin-top:36px;font-size:clamp(48px,7vw,96px)">People</h1><p class="note" style="margin-top:12px">${PEOPLE.length} of roughly 150 major figures are drafted, in ${ROLES.length} groups. Peter and John the Baptist have full pages. The real build draws on 3,067 people from open data.</p>
 <div class="strip" style="margin-top:20px">${ROLES.map(r=>`<a class="gl" href="#r-${slug(r)}"><span class="gi">${ico(RI[r],16)}</span><span>${r}</span><span class="note" style="font-size:12px">${PEOPLE.filter(p=>p[3]===r).length}</span></a>`).join('')}</div>
 ${ROLES.map(r=>`<div class="sect" id="r-${slug(r)}"><div><span class="gi">${ico(RI[r],24)}</span><div class="lab" style="color:var(--ink);margin-top:12px">${r}</div>${r==='Apostles'?art('B3','art-margin'):''}</div><div class="list">${PEOPLE.filter(p=>p[3]===r).map(([n,d,w])=>`<a class="item" href="/people/${slug(n)}"><span><span style="font-size:21px;font-weight:500">${n}${FULL[slug(n)]?` <span class="tag" style="color:var(--accent)">full page</span>`:''}</span><span class="sub">${d}</span></span><span class="note" style="text-align:right;max-width:260px">${w}</span></a>`).join('')}</div></div>`).join('')}</div>`}

export function person(s){let p=PEOPLE.find(x=>slug(x[0])===s);if(!p){const nm=s.split('-').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ');p=[nm,'Appears in Matthew. Page not yet written.','See the chapters below','']}const f=FULL[s];const first=p[0].split(' ')[0];const inMt=MT.ch.filter(c=>c[5]&&(c[5].people||[]).includes(p[0])).map(c=>c[0]);
 return `<div class="wrap"><div class="crumb"><a href="/explore">Explore</a><span>/</span><a href="/people">People</a><span>/</span><span style="color:var(--ink)">${p[0]}</span></div>
 <div class="poster" style="margin-top:28px;background-image:${pattern('person','#4d6f95')},linear-gradient(120deg,color-mix(in srgb,#4d6f95 30%,var(--bg)) 0%,var(--bg) 62%)"><span class="wmk" style="color:#4d6f95">${ico('person',360)}</span><div><div class="lab" style="color:#8fb3dc">Person</div><h1 class="h1" style="margin-top:8px">${p[0]}</h1><p style="font-size:22px;margin:14px 0 0;max-width:720px;font-style:italic">${p[1]}</p></div><span class="gi poster-ico">${ico('person',72)}</span></div>
 ${sect('Who',f?`<p style="margin:0;max-width:720px">${f.who}</p>`:`<div class="stub">Not yet written for ${p[0]}.</div>`,'','person')}
 ${f?sect('Relationships',`<div class="grid2">${f.rel.map(([n,r])=>`<div style="display:flex;gap:12px;align-items:baseline;padding:10px 0;border-bottom:1px solid var(--line)"><span style="font-weight:500">${n}</span><span style="color:var(--dim);font-size:15px">${r}</span></div>`).join('')}</div>`,'','link'):''}
 ${sect('Arc',f?`<div class="tl">${f.arc.map(([t,r,d])=>`<div><div style="display:flex;gap:12px;align-items:baseline;flex-wrap:wrap"><span style="font-size:21px;font-weight:500">${t}</span><span class="tag">${r}</span></div><p style="margin:4px 0 0;color:var(--dim)">${d}</p></div>`).join('')}</div>`:`<div class="stub">Not yet written.</div>`,'','road')}
 ${f?sect('In their own words',`<div class="grid2">${f.quotes.map(([r,t])=>verseCard(r,t)).join('')}</div>`,'','quote'):''}
 ${sect(`Where ${first} appears`,`<p style="margin:0 0 14px;color:var(--dim)">${p[2]}</p>${f?Object.entries(f.books).map(([bs,chs])=>{const bb=bySlug(bs);return `<div style="display:grid;grid-template-columns:110px minmax(0,1fr);gap:14px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)"><a href="/book/${bs}" style="color:var(--ink);font-weight:500">${bb.name}<span class="note" style="display:block">${chs.length} of ${bb.ch} chapters</span></a><div style="display:flex;gap:2px;flex-wrap:wrap">${Array.from({length:bb.ch},(_,i)=>i+1).map(ch=>`<a href="/book/${bs}/${ch}" title="${bb.name} ${ch}" style="width:${bb.ch>30?14:20}px;height:${bb.ch>30?14:20}px;display:inline-flex;align-items:center;justify-content:center;font-size:9px;font-family:'Instrument Sans',sans-serif;background:${chs.includes(ch)?'#4d6f95':'var(--line2)'};color:${chs.includes(ch)?'#fff':'transparent'};border-radius:2px">${ch}</a>`).join('')}</div></div>`}).join(''):inMt.length?`<div class="lab" style="margin-bottom:8px">In Matthew</div><div class="mini" style="max-width:560px">${MT.ch.map(c=>`<a href="/book/matthew/${c[0]}" style="background:${inMt.includes(c[0])?'#4d6f95':'var(--line2)'};color:${inMt.includes(c[0])?'#fff':'var(--dim)'}">${c[0]}</a>`).join('')}</div>`:''}<p class="note" style="margin-top:10px">Blue: chapters where ${first} is named. The real build fills every book from open people data.</p>`,'','map')}
 ${f?sect('Where traditions differ',`<p style="margin:0;max-width:720px;color:var(--dim)">${f.trad}</p>`,'','scales'):''}
 </div>`}

export let PF='all';export function setPF(v){PF=v}
export function parables(){const has=(r,g)=>r.includes(g);const themes=[...new Set(PTHEME)];const rows=PARABLES.map((p,i)=>[...p,PTHEME[i]]).filter(p=>PF==='all'||p[3]===PF);return `<div class="wrap">${art('B1','art-page-heading')}<div class="crumb"><a href="/explore">Explore</a><span>/</span><span style="color:var(--ink)">Parables</span></div><h1 class="h1" style="margin-top:36px;font-size:clamp(48px,7vw,96px)">Parables of Jesus</h1><p style="font-size:22px;color:var(--dim);margin:14px 0 0;max-width:720px">${PARABLES.length} parables. Counts differ by how you draw the line between a parable and a saying; this list uses the common set. John records none.</p>
 <div class="grid3" style="margin-top:28px">${[['Matthew','Matthew'],['Mark','Mark'],['Luke','Luke']].map(([g])=>`<div class="card" style="padding:16px 18px;display:flex;gap:14px;align-items:center"><span class="gi" style="color:#4d6f95">${ico('fish',20)}</span><div><div style="font-size:28px;line-height:1">${PARABLES.filter(p=>has(p[1],g)).length}</div><div class="note">in ${g} · ${PARABLES.filter(p=>has(p[1],g)&&!['Matthew','Mark','Luke'].filter(x=>x!==g).some(x=>has(p[1],x))).length} only there</div></div></div>`).join('')}</div>
 <div class="strip" style="margin-top:24px"><button class="opt ${PF==='all'?'on':''}" data-pf="all" style="border-radius:999px">All ${PARABLES.length}</button>${themes.map(t=>`<button class="opt ${PF===t?'on':''}" data-pf="${t}" style="border-radius:999px;text-transform:capitalize">${t} <span class="note">${PTHEME.filter(x=>x===t).length}</span></button>`).join('')}</div>
 <div class="tablewrap" style="margin-top:16px"><table><thead><tr><th>Parable</th><th>Mt · Mk · Lk</th><th>Where it is told</th><th>What it teaches</th></tr></thead><tbody>${rows.map(([n,r,d,t])=>`<tr><td style="font-weight:500;font-size:17px">${n}<span class="note" style="display:block;text-transform:capitalize">${t}</span>${/mustard/i.test(n)?art('B4','art-parable'):/lost sheep/i.test(n)?art('B2','art-parable'):/sower/i.test(n)?art('B1','art-parable'):''}</td><td><span class="matrix"><span class="${has(r,'Matthew')?'y':''}"></span><span class="${has(r,'Mark')?'y':''}"></span><span class="${has(r,'Luke')?'y':''}"></span></span></td><td class="note" style="font-size:14px">${r.split(';').map(x=>{const m=x.trim().match(/^(Matthew|Mark|Luke) (\d+)/);return m?`<a href="/book/${m[1].toLowerCase()}/${m[2]}">${x.trim()}</a>`:x.trim()}).join('; ')}</td><td style="color:var(--dim)">${d}</td></tr>`).join('')}</tbody></table></div></div>`}

export function places(){const idx={};MT.ch.forEach(c=>(c[5]&&c[5].places||[]).forEach(p=>{(idx[p]=idx[p]||[]).push(c[0])}));
 return `<div class="wrap">${art('C3','art-page-heading')}<div class="crumb"><a href="/explore">Explore</a><span>/</span><span style="color:var(--ink)">Places</span></div><h1 class="h1" style="margin-top:36px;font-size:clamp(48px,7vw,96px)">Places</h1><p style="font-size:22px;color:var(--dim);margin:14px 0 0;max-width:720px">The land of the Gospels, drawn to real coordinates. Red points appear in Matthew. The real build uses OpenBible’s 1,341 geocoded places on a proper map with terrain.</p>
 <div style="display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:32px;margin-top:32px;align-items:start" class="grid2"><div><div class="card" style="padding:8px">${mapSvg(Object.keys(idx),true)}</div><div class="card" style="padding:14px 16px;margin-top:12px"><div class="lab" style="margin-bottom:8px">Jesus’ movements in Matthew</div><div style="display:flex;gap:6px;flex-wrap:wrap">${JOURNEY.map(([n,r],i)=>`<a class="chip" href="/book/matthew/${r.split(':')[0]}"><span style="width:16px;height:16px;border-radius:50%;background:var(--accent);color:var(--bg);display:inline-flex;align-items:center;justify-content:center;font-size:9px;font-weight:600">${i+1}</span>${n} <span class="note">${r}</span></a>`).join('')}</div><div class="note" style="margin-top:8px">Egypt (2:14) lies off the map to the south west.</div></div></div>
 <div><div class="lab" style="margin-bottom:8px">In Matthew</div><div class="list">${Object.entries(idx).sort((a,b)=>b[1].length-a[1].length).map(([p,chs])=>`<div class="item"><span><span style="font-weight:500;display:inline-flex;gap:8px;align-items:center">${ico('pin',14)}${p}</span><span class="sub">${chs.length===1?'Chapter':'Chapters'} ${chs.map(c=>`<a href="/book/matthew/${c}">${c}</a>`).join(', ')}</span></span></div>`).join('')}</div>
 <div class="lab" style="margin:24px 0 8px">Beyond this map</div><div class="cal">${BEYOND.map(([p,w])=>`<span title="${w}">${p}</span>`).join('')}</div></div></div></div>`}

export function timeline(){return `<div class="wrap">${art('C4','art-page-heading')}<div class="crumb"><a href="/explore">Explore</a><span>/</span><span style="color:var(--ink)">Major events</span></div><h1 class="h1" style="margin-top:36px;font-size:clamp(48px,7vw,96px)">Major events</h1><p style="font-size:22px;color:var(--dim);margin:14px 0 0;max-width:720px">Two thousand years on one line, then the first century on its own. A bar instead of a dot means scholars disagree about the date.</p>
 <div class="card" style="padding:20px 16px 8px;margin-top:32px">${timelineSvg()}</div>
 <div class="lab" style="margin:24px 0 8px">The first century, zoomed</div>
 <div class="card" style="padding:20px 16px 8px">${centurySvg()}</div>
 <div class="tl" style="margin-top:48px;max-width:800px">${EVENTS.map(([a,z,d,t,r])=>`<div><div class="lab" style="color:var(--accent)">${d}</div><div style="font-size:22px;font-weight:500;line-height:1.2;margin-top:2px">${t}</div><div class="note" style="margin-top:2px">${r}</div></div>`).join('')}</div></div>`}

export function commandments(){return `<div class="wrap">${art('D3','art-page-heading')}<div class="crumb"><a href="/explore">Explore</a><span>/</span><span style="color:var(--ink)">Commandments and teachings</span></div><h1 class="h1" style="margin-top:36px;font-size:clamp(48px,7vw,96px)">Commandments</h1><p style="font-size:22px;color:var(--dim);margin:14px 0 0;max-width:720px">"Commandments" can mean three different lists. All three are here so the word never hides an assumption.</p>
 <div class="grid3" style="margin-top:40px">${COMMANDS.map(([t,r,items],i)=>`<div class="card" style="padding:22px 24px"><span class="gi">${ico(['tablets','scales','mountain'][i],22)}</span><div style="font-size:22px;font-weight:500;line-height:1.2;margin-top:12px">${t}</div><div class="note" style="margin-top:4px">${r}</div><ol style="margin:16px 0 0;padding-left:22px;color:var(--ink);font-size:16px;line-height:1.6">${items.map(i=>`<li>${i}</li>`).join('')}</ol></div>`).join('')}</div>
 ${sect('The Beatitudes',`<div class="grid2">${BEAT.map(([r,t])=>verseCard(r,t)).join('')}</div>`,'Eight blessings that open the Sermon on the Mount. Each one is a flashcard away.','mountain')}
 ${sect('The Lord’s Prayer',verseCard(LORDS[0],LORDS[1]),'','heart')}
 ${sect('Teachings',`<div class="grid2">${[['Sermon on the Mount','Matthew 5 to 7','matthew/5','mountain'],['The mission discourse','Matthew 10','matthew/10','road'],['Parables of the kingdom','Matthew 13','matthew/13','seed'],['Life in the community','Matthew 18','matthew/18','person'],['The Olivet discourse','Matthew 24 to 25','matthew/24','flame'],['The upper room discourse','John 13 to 17','john/13','lamp']].map(([t,r,h,i])=>`<a class="card" href="/book/${h}" style="padding:18px 20px;color:var(--ink);display:flex;gap:14px;align-items:center"><span class="gi">${ico(i,20)}</span><div><div style="font-size:20px;font-weight:500">${t}</div><div class="note">${r}</div></div></a>`).join('')}</div>`,'','mountain')}</div>`}

/* ---- Memorise ---- */
export let MEM={deck:0,mode:'cards',i:0,flip:false,result:null,test:null,filter:'all',textFirst:false,order:null};
export function cardsOf(d){const cs=d.cards.filter(c=>MEM.filter==='all'||(S.CSTAT[c[0]]||'new')===MEM.filter);if(MEM.order&&MEM.order.length===cs.length)return MEM.order.map(i=>cs[i]);return cs}
export function memorize(){const d=S.DECKS[MEM.deck]||S.DECKS[0];MEM.deck=S.DECKS.indexOf(d);const cs=cardsOf(d);const cnt=k=>d.cards.filter(c=>(S.CSTAT[c[0]]||'new')===k).length;
 return `<div class="wrap">${art('A3','art-page-heading')}<div class="lab">Verses you are learning</div><h1 class="h1" style="margin-top:8px;font-size:clamp(48px,7vw,96px)">Memorise</h1>
 <div class="sect"><div><div class="lab" style="color:var(--ink)">Decks</div><div style="display:flex;flex-direction:column;gap:8px;margin-top:12px">${S.DECKS.map((x,i)=>`<button class="opt" data-deck="${i}" style="text-align:left;border-color:${i===MEM.deck?'var(--ink)':'var(--line)'}">${esc(x.name)}<span class="note" style="display:block">${x.cards.length} verses</span></button>`).join('')}<button class="btn ghost" id="newdeck" style="justify-content:center">${ico('plus',14)} New deck</button></div>
  <div class="lab" style="color:var(--ink);margin-top:28px">Sort by how well you know them</div><div style="display:flex;flex-direction:column;gap:6px;margin-top:10px">${[['all','All',d.cards.length],['new','Not yet tried',cnt('new')],['learning','Still learning',cnt('learning')],['known','Know it',cnt('known')]].map(([k,l,n])=>`<button class="opt" data-filter="${k}" style="text-align:left;display:flex;justify-content:space-between;border-color:${MEM.filter===k?'var(--ink)':'var(--line)'}"><span>${l}</span><span class="note">${n}</span></button>`).join('')}</div></div>
 <div>
  <div style="display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap"><h2 style="font-size:32px">${esc(d.name)}</h2><div class="modes">${[['cards','Flashcards'],['list','All verses']].map(([m,l])=>`<button data-mode="${m}" class="${MEM.mode===m?'on':''}">${l}</button>`).join('')}</div></div>
  <div style="margin-top:24px" id="memarea">${memArea(d,cs)}</div>
  <div class="card" style="margin-top:32px;padding:20px 22px"><div class="lab">Add a verse</div><div class="note" style="margin:4px 0 12px">In the real build you only type the reference and the NLT text is fetched for you. Every verse in the reader also has a memorise button.</div><div style="display:grid;grid-template-columns:200px minmax(0,1fr);gap:10px"><input type="text" id="vref" placeholder="Matthew 7:7"><input type="text" id="vtxt" placeholder="Ask, and it will be given to you..."></div><div style="margin-top:10px"><button class="btn" id="addcard">Add to ${esc(d.name)}</button></div></div>
 </div></div></div>`}
export function statBtns(ref){const s=S.CSTAT[ref]||'new';return `<div class="stat"><button class="opt l ${s==='learning'?'on':''}" data-stat="learning" data-ref="${esc(ref)}">Still learning</button><button class="opt k ${s==='known'?'on':''}" data-stat="known" data-ref="${esc(ref)}">${ico('check',12)} Know it</button></div>`}
export function memArea(d,cs){if(!d.cards.length)return`<div class="stub">No verses yet. Add one below, or press "Memorise this" on any key verse.</div>`;if(!cs.length)return`<div class="stub">Nothing in this group yet.</div>`;const c=cs[Math.min(MEM.i,cs.length-1)];
 if(MEM.mode==='cards'){const front=MEM.textFirst?`<div><div class="lab">Which verse is this?</div><div style="font-size:22px;line-height:1.5;margin-top:10px">${esc(c[1])}</div></div>`:`<div><div class="lab">Reference</div><div class="disp" style="font-size:44px;margin-top:8px">${esc(c[0])}</div><div class="note" style="margin-top:14px">Click or press space to flip</div></div>`;const back=MEM.textFirst?`<div><div class="lab">Reference</div><div class="disp" style="font-size:44px;margin-top:8px">${esc(c[0])}</div></div>`:`<div><div class="lab">${esc(c[0])}</div><div style="font-size:24px;line-height:1.5;margin-top:10px">${esc(c[1])}</div></div>`;
  return`<div style="display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:12px"><div style="display:flex;gap:4px;flex-wrap:wrap">${cs.map((x,i)=>`<span title="${esc(x[0])}" style="width:${cs.length>20?6:10}px;height:6px;border-radius:3px;background:${i===MEM.i?'var(--ink)':(S.CSTAT[x[0]]||'new')==='known'?'var(--ok)':(S.CSTAT[x[0]]||'new')==='learning'?'var(--accent)':'var(--line)'}"></span>`).join('')}</div><div style="display:flex;gap:8px"><button class="opt" id="shuffle" style="border-radius:999px">Shuffle</button><button class="opt ${MEM.textFirst?'on':''}" id="textfirst" style="border-radius:999px">Text first</button></div></div>
  <div class="fc ${MEM.flip?'flip':''}" id="fc" tabindex="0" role="button" aria-label="Flip card"><div class="in"><div class="face">${art('D5','art-corner')}<span class="wm">${ico('quote',64)}</span>${front}</div><div class="face back">${back}</div></div></div>
  <div style="display:flex;justify-content:space-between;align-items:center;margin-top:14px;flex-wrap:wrap;gap:10px"><button class="btn ghost" id="prev">← Previous</button><span class="note">${MEM.i+1} of ${cs.length} · arrow keys move, space flips</span><button class="btn ghost" id="next">Next →</button></div>${statBtns(c[0])}`}
 return`<div class="list">${cs.map((x,i)=>`<div class="item"><span><span style="font-weight:500">${esc(x[0])}</span> <span class="tag" style="color:${(S.CSTAT[x[0]]||'new')==='known'?'var(--ok)':(S.CSTAT[x[0]]||'new')==='learning'?'var(--accent)':'var(--dim)'}">${{new:'not yet tried',learning:'still learning',known:'know it'}[S.CSTAT[x[0]]||'new']}</span><span class="sub">${esc(x[1])}</span></span><button class="opt" data-del="${d.cards.indexOf(x)}" style="border:none;background:none;color:var(--dim);font-size:13px;text-decoration:underline;padding:0">Remove</button></div>`).join('')}</div>`}
export function library(){return `<div class="wrap">${art('A6','art-page-heading')}<div class="lab">The hub</div><h1 class="h1" style="margin-top:8px;font-size:clamp(48px,7vw,96px)">Library</h1><p style="font-size:22px;color:var(--dim);margin:14px 0 0;max-width:760px">Nothing here is rebuilt. These are the sources this platform links into, on every book and every chapter. Adding a new one is one URL pattern.</p>
 <div class="grid2" style="margin-top:32px">${[['ALsluAKBZ-c','The Old Testament in one video','Overview'],['Q0BrP8bqj0c','The New Testament in one video','Overview'],['GQI72THyO5I','Genesis 1 to 11','Book overview'],['3Dv4-n6OYGI','Matthew 1 to 13','Book overview']].map(([id,t,d])=>video(id,t,d)).join('')}</div>
 <p class="note" style="margin-top:10px">Videos by <a href="https://bibleproject.com" target="_blank" rel="noopener">BibleProject</a>, embedded with credit as their terms require.</p>
 <div class="list" style="margin-top:32px">${RESOURCES.map(([n,d,u,h,i])=>`<a class="item" href="${u}" ${u==='#'?'':'target="_blank" rel="noopener"'}><span style="display:flex;gap:14px;align-items:flex-start"><span class="gi" style="flex:none">${ico(i,20)}</span><span><span style="font-size:22px;font-weight:500">${n}</span><span class="sub">${d}</span></span></span><span class="note" style="text-align:right;max-width:260px">${h}</span></a>`).join('')}</div>
 ${sect('Try it',`<div class="note" style="margin-bottom:10px">Pick any chapter and every source opens to that chapter.</div><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center"><select id="lbbook" style="width:auto">${BOOKS.map(b=>`<option value="${b.slug}" ${b.slug==='matthew'?'selected':''}>${b.name}</option>`).join('')}</select><input type="text" id="lbch" value="5" style="width:80px"><button class="btn ghost" id="lbgo">Build links</button></div><div id="lbout" style="margin-top:14px">${extLinks(bySlug('matthew'),5)}</div>`,'','link')}</div>`}

export function search(q){q=decodeURIComponent(q||'').trim();const Q=q.toLowerCase();const hit=s=>s&&s.toLowerCase().includes(Q);const R=[];
 if(Q){BOOKS.filter(b=>hit(b.name)||hit(THESES[b.name])).forEach(b=>R.push(['Book',b.name,THESES[b.name]||b.genre,`/book/${b.slug}`,GICON[b.gid]]));
 MT.ch.filter(c=>hit(c[1])||hit(c[3])).forEach(c=>R.push(['Matthew '+c[0],c[1],c[3],`/book/matthew/${c[0]}`,SICON[c[2]]]));
 PEOPLE.filter(p=>hit(p[0])||hit(p[1])||hit(p[3])).forEach(p=>R.push(['Person',p[0],p[1],`/people/${slug(p[0])}`,'person']));
 PARABLES.filter(p=>hit(p[0])||hit(p[2])).forEach(p=>R.push(['Parable',p[0],p[1],'/parables','seed']));
 EVENTS.filter(e=>hit(e[3])).forEach(e=>R.push(['Event',e[3],e[2]+' · '+e[4],'/timeline','flag']));
 PLACES.filter(p=>hit(p[0])).forEach(p=>R.push(['Place',p[0],'On the map','/places','pin']));
 Object.entries(KEYV).filter(([r,t])=>hit(t)).forEach(([r,t])=>R.push(['Verse','Matthew '+r,t,`/book/matthew/${r.split(':')[0]}`,'quote']));
 RESOURCES.filter(r=>hit(r[0])||hit(r[1])).forEach(r=>R.push(['Resource',r[0],r[1],'/library',r[4]]));}
 return `<div class="wrap"><div class="lab">Search</div><h1 class="h2" style="margin-top:8px">${q?`“${esc(q)}”`:'Type something to search'}</h1><p class="note" style="margin-top:10px">${R.length} result${R.length===1?'':'s'} across books, chapters, people, parables, events, places, verses and resources.</p>
 <div class="list" style="margin-top:24px">${R.map(([k,t,d,h,i])=>`<a class="item" href="${h}"><span style="display:flex;gap:14px;align-items:flex-start"><span class="gi" style="flex:none">${ico(i,20)}</span><span><span class="lab" style="font-size:11px">${k}</span><span style="font-size:20px;font-weight:500;display:block">${esc(t)}</span><span class="sub">${esc(d)}</span></span></span></a>`).join('')||`<div class="stub">Nothing matched. In the real build search also covers every verse of the Bible.</div>`}</div></div>`}

export function notes(){const list=Object.entries(S.NOTES).filter(([k,v])=>v.trim()).reverse();return `<div class="wrap">${art('A4','art-page-heading')}<div class="lab">Everything you wrote</div><h1 class="h1" style="margin-top:8px;font-size:clamp(48px,7vw,96px)">Notes</h1><p class="note" style="margin-top:12px">${list.length} note${list.length===1?'':'s'}. Each one lives on its chapter page too. In the real build these sync to your account and can be exported.</p>
 <div style="margin-top:32px;display:flex;flex-direction:column;gap:12px">${list.map(([k,v])=>{const [bs,ch]=k.split(':');const b=bySlug(bs);const c=bs==='matthew'?MT.ch[ch-1]:null;return `<a class="card" href="/book/${bs}/${ch}" style="padding:18px 22px;color:var(--ink);display:grid;grid-template-columns:180px minmax(0,1fr);gap:20px"><span><span class="lab" style="color:var(--accent)">${b?b.name:bs} ${ch}</span>${c?`<span style="display:block;font-weight:500;margin-top:4px">${c[1]}</span>`:''}</span><span style="white-space:pre-wrap;color:var(--dim);font-size:17px">${esc(v)}</span></a>`}).join('')||`<div class="stub emp">${ico('pen',18)} No notes yet. Open any chapter and write in the notes box.</div>${art('D6','art-rest')}`}</div></div>`}
export function notFound(){return `<div class="wrap"><h1 class="h1">Not found</h1><p><a href="/">Back to the canon</a></p></div>`}

