// Finds verse-level Scripture references in free text, including common abbreviations.
import { BOOK_TABLE, bookFromName } from './books.js';
const ABBR={gen:'Genesis',ge:'Genesis',gn:'Genesis',ex:'Exodus',exo:'Exodus',exod:'Exodus',lev:'Leviticus',le:'Leviticus',lv:'Leviticus',num:'Numbers',nu:'Numbers',nm:'Numbers',deut:'Deuteronomy',deu:'Deuteronomy',dt:'Deuteronomy',josh:'Joshua',jos:'Joshua',judg:'Judges',jdg:'Judges',jgs:'Judges',ru:'Ruth',rth:'Ruth','1 sam':'1 Samuel','2 sam':'2 Samuel','1 sa':'1 Samuel','2 sa':'2 Samuel','1 kgs':'1 Kings','2 kgs':'2 Kings','1 ki':'1 Kings','2 ki':'2 Kings','1 chr':'1 Chronicles','2 chr':'2 Chronicles','1 chron':'1 Chronicles','2 chron':'2 Chronicles',ezr:'Ezra',neh:'Nehemiah',ne:'Nehemiah',est:'Esther',esth:'Esther',jb:'Job',ps:'Psalms',psa:'Psalms',psalm:'Psalms',pss:'Psalms',prov:'Proverbs',pr:'Proverbs',pro:'Proverbs',eccl:'Ecclesiastes',ecc:'Ecclesiastes',ec:'Ecclesiastes',song:'Song of Songs','song of solomon':'Song of Songs',sos:'Song of Songs',isa:'Isaiah',is:'Isaiah',jer:'Jeremiah',je:'Jeremiah',lam:'Lamentations',la:'Lamentations',ezek:'Ezekiel',eze:'Ezekiel',ezk:'Ezekiel',dan:'Daniel',da:'Daniel',dn:'Daniel',hos:'Hosea',ho:'Hosea',joe:'Joel',jl:'Joel',am:'Amos',amo:'Amos',obad:'Obadiah',ob:'Obadiah',oba:'Obadiah',jon:'Jonah',jnh:'Jonah',mic:'Micah',mi:'Micah',nah:'Nahum',na:'Nahum',hab:'Habakkuk',hb:'Habakkuk',zeph:'Zephaniah',zep:'Zephaniah',hag:'Haggai',hg:'Haggai',zech:'Zechariah',zec:'Zechariah',mal:'Malachi',ml:'Malachi',matt:'Matthew',mt:'Matthew',mat:'Matthew',mk:'Mark',mrk:'Mark',mr:'Mark',lk:'Luke',luk:'Luke',lu:'Luke',jn:'John',jhn:'John',joh:'John',ac:'Acts',act:'Acts',rom:'Romans',ro:'Romans',rm:'Romans','1 cor':'1 Corinthians','2 cor':'2 Corinthians','1 co':'1 Corinthians','2 co':'2 Corinthians',gal:'Galatians',ga:'Galatians',eph:'Ephesians',ep:'Ephesians',phil:'Philippians',php:'Philippians',col:'Colossians','1 thess':'1 Thessalonians','2 thess':'2 Thessalonians','1 th':'1 Thessalonians','2 th':'2 Thessalonians','1 tim':'1 Timothy','2 tim':'2 Timothy','1 ti':'1 Timothy','2 ti':'2 Timothy',tit:'Titus',phlm:'Philemon',philem:'Philemon',phm:'Philemon',heb:'Hebrews',jas:'James',jm:'James','1 pet':'1 Peter','2 pet':'2 Peter','1 pe':'1 Peter','2 pe':'2 Peter','1 jn':'1 John','2 jn':'2 John','3 jn':'3 John','1 jo':'1 John','2 jo':'2 John','3 jo':'3 John',jud:'Jude',jde:'Jude',rev:'Revelation',re:'Revelation',rv:'Revelation'};
const NAMES=[...BOOK_TABLE.map(b=>b.name),'Psalm','Song of Solomon',...Object.keys(ABBR)].sort((a,b)=>b.length-a.length).map(n=>n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));
const RX=new RegExp(`(?<![A-Za-z])(${NAMES.join('|')})\\.?\\s+(\\d{1,3})(?::(\\d{1,3})(?:\\s*[-–]\\s*(?:(\\d{1,3}):)?(\\d{1,3}))?)?(?![\\d:])`,'gi');
function resolve(name){ const k=name.toLowerCase().replace(/\.$/,'').replace(/\s+/g,' '); return bookFromName(ABBR[k]||name)||bookFromName(name[0].toUpperCase()+name.slice(1).toLowerCase())||bookFromName(name.replace(/\b\w/g,c=>c.toUpperCase())); }
// -> [{ book, ch, v1, v2, label }] with verse numbers optional (chapter-only refs have v1=null)
export function findRefs(text){
  const out=[]; let m; RX.lastIndex=0; const s=String(text||'');
  while((m=RX.exec(s))){ const book=resolve(m[1]); if(!book) continue; const ch=+m[2]; if(ch<1||ch>book.ch) continue;
    if(m[4]&&+m[4]!==ch){ out.push({ book, ch, v1:m[3]?+m[3]:null, v2:null, label:`${book.name} ${ch}${m[3]?':'+m[3]:''}` }); continue; }
    const v1=m[3]?+m[3]:null, v2=m[5]?+m[5]:v1; out.push({ book, ch, v1, v2, label:`${book.name} ${ch}${v1?':'+v1+(v2&&v2!==v1?'-'+v2:''):''}` }); }
  return out;
}
export { RX as REF_RX };
