// Table charts: each is columns plus rows, with any cell that looks like a reference turned into a link by the renderer.
export const CHARTS=[
{
  id:'feasts', title:'The Jewish Year', subtitle:'The feasts of Leviticus 23, when they fell, what they remembered, and where the New Testament picks them up',
  intro:'Israel’s year turned on seven appointed times, three of them pilgrimage feasts when every man went up to Jerusalem. The spring feasts cluster around Passover, the autumn feasts around the Day of Atonement, with the long dry summer between. Every one of them is in the background of a Gospel scene.',
  books:['Leviticus','Deuteronomy','John','Acts'],
  columns:['Feast','When','What it remembered or marked','Text','In the New Testament'],
  rows:[
    ['Sabbath','Every seventh day','Creation rest and the exodus rescue. No work, for anyone, including servants and animals.','Exodus 20:8-11; Deuteronomy 5:12-15; Leviticus 23:3','Jesus is Lord of the Sabbath (Matthew 12:8); the rest that remains (Hebrews 4:9-10).'],
    ['Passover (Pesach)','14 Nisan (March or April), at twilight','The lamb whose blood marked the doors in Egypt. Eaten in haste with bitter herbs and unleavened bread.','Exodus 12; Leviticus 23:5; Deuteronomy 16:1-8','The Last Supper is a Passover meal (Luke 22:15); "Christ, our Passover lamb, has been sacrificed" (1 Corinthians 5:7); John dates the crucifixion to the slaughter of the lambs (John 19:14).'],
    ['Unleavened Bread','15 to 21 Nisan, seven days','The hurried departure, no time for dough to rise. Every trace of leaven removed from the house.','Exodus 12:15-20; Leviticus 23:6-8','"Get rid of the old yeast" (1 Corinthians 5:6-8); Jesus lies in the tomb during this feast.'],
    ['Firstfruits','The day after the Sabbath of Passover week','The first sheaf of the barley harvest waved before the LORD before anyone ate the new crop.','Leviticus 23:9-14','Christ raised "the firstfruits of those who have fallen asleep" (1 Corinthians 15:20-23), on this very day.'],
    ['Weeks (Shavuot, Pentecost)','Fifty days after Firstfruits, 6 Sivan (May or June)','The wheat harvest; two loaves baked with leaven. Later tradition also remembered the giving of the law at Sinai.','Leviticus 23:15-22; Deuteronomy 16:9-12','The Spirit poured out and three thousand baptised (Acts 2). Paul hurried to keep it (Acts 20:16).'],
    ['Trumpets (Rosh Hashanah)','1 Tishri (September or October)','A day of trumpet blasts opening the seventh month, the civil new year.','Leviticus 23:23-25; Numbers 29:1-6','The trumpet at the return of Christ (1 Thessalonians 4:16; 1 Corinthians 15:52) is often read against it.'],
    ['Day of Atonement (Yom Kippur)','10 Tishri','The one day the high priest entered the Most Holy Place, with blood for himself and the people; the scapegoat sent into the wilderness. A fast, not a feast.','Leviticus 16; Leviticus 23:26-32','Hebrews 9 to 10 reads the whole day as a picture of the cross: one priest, one sacrifice, once for all.'],
    ['Tabernacles (Sukkot, Booths)','15 to 21 Tishri, with an eighth day','Living in shelters for a week to remember the wilderness; the end of the harvest; water drawn and poured out at the altar; the temple lit at night.','Leviticus 23:33-43; Deuteronomy 16:13-15; Zechariah 14:16','On the last day Jesus cried "let anyone who is thirsty come to me" (John 7:37-39) and "I am the light of the world" (John 8:12). The Word "tabernacled" among us (John 1:14). God will dwell with his people (Revelation 21:3).'],
    ['Sabbath year','Every seventh year','The land rested and debts were released.','Leviticus 25:1-7; Deuteronomy 15:1-11','Jesus’ Nazareth sermon announces "the year of the Lord’s favour" (Luke 4:19).'],
    ['Jubilee','Every fiftieth year, proclaimed on the Day of Atonement','Land returned to its family, slaves freed, debts cancelled. Never recorded as actually kept.','Leviticus 25:8-55; Isaiah 61:1-2','Isaiah’s Jubilee language is what Jesus read at Nazareth (Luke 4:18-21).'],
    ['Purim','14 Adar (February or March)','Deliverance from Haman in Persia. Not in Leviticus; instituted in Esther.','Esther 9:20-32','Not mentioned in the New Testament.'],
    ['Dedication (Hanukkah)','25 Kislev (December), eight days','The cleansing of the temple by Judas Maccabeus in 164 BC after Antiochus defiled it. Between the Testaments; in 1 Maccabees, not the Hebrew Bible.','1 Maccabees 4:36-59','Jesus walks in Solomon’s Portico at this feast and says "I and the Father are one" (John 10:22-30).'],
  ],
  notes:[['Two calendars','The religious year began in spring with Nisan (Exodus 12:2); the civil year began in autumn with Tishri. Both are lunar months, so the feasts drift against our calendar by up to a month.'],['Three pilgrimages','Passover, Weeks and Tabernacles were the feasts every male was to attend in Jerusalem (Deuteronomy 16:16). That is why Jesus is so often in Jerusalem in John, and why the city was so crowded at the crucifixion and at Pentecost.']],
},
{
  id:'offerings', title:'The Five Offerings', subtitle:'Leviticus 1 to 7: what was brought, why, and who ate it',
  intro:'Leviticus opens with five kinds of offering, each with its own procedure. Two are about gratitude and fellowship, two about sin, and one, the burnt offering, about total devotion. Every animal was killed at the altar by the worshipper’s own hand. The book assumes you know why; Hebrews explains.',
  books:['Leviticus','Hebrews'],
  columns:['Offering','Hebrew','What was brought','Why','Who ate it','Text','New Testament echo'],
  rows:[
    ['Burnt offering','olah, "that which goes up"','A male without defect: bull, ram, goat, or dove or pigeon for the poor. Skinned, cut up, and wholly burned.','Atonement and complete dedication. The daily morning and evening sacrifice was a burnt offering.','No one. The whole animal went up in smoke; only the skin went to the priest.','Leviticus 1; Leviticus 6:8-13; Exodus 29:38-42','Christ "gave himself up for us as a fragrant offering" (Ephesians 5:2); "offer your bodies as a living sacrifice" (Romans 12:1).'],
    ['Grain offering','minchah, "gift, tribute"','Fine flour with oil and frankincense, or baked cakes; no leaven or honey; always salted. A handful burned, the rest to the priests.','Thanksgiving and homage; the fruit of work offered back. Usually accompanied a burnt offering.','The priests, in the court.','Leviticus 2; Leviticus 6:14-23','Jesus the bread of life (John 6:35); the Gentiles’ offering "acceptable to God" (Romans 15:16).'],
    ['Fellowship (peace) offering','shelamim, from shalom','Any animal from the herd or flock, male or female. Fat burned, breast and thigh to the priests, the rest eaten by the worshipper and family that day.','Thanksgiving, a vow fulfilled, or simple free will. The only offering the worshipper ate: a meal with God.','The priests and the worshipper’s household together.','Leviticus 3; Leviticus 7:11-36; Deuteronomy 12:7','The Lord’s Supper as fellowship (1 Corinthians 10:16-18); "he himself is our peace" (Ephesians 2:14).'],
    ['Sin (purification) offering','chattat','Graded by the sinner: a bull for the high priest or the whole congregation, a male goat for a leader, a female goat or lamb for a commoner, two birds or flour for the poor. Blood on the horns of the altar; on the Day of Atonement, inside the veil.','Unintentional sin and ritual impurity. It cleansed the sanctuary from the pollution sin caused.','The priests, unless the blood had gone into the tent; then it was burned outside the camp.','Leviticus 4:1 to 5:13; Leviticus 6:24-30; Leviticus 16','"God made him who had no sin to be sin for us" (2 Corinthians 5:21); Jesus suffered "outside the city gate" like the sin offering (Hebrews 13:11-12).'],
    ['Guilt (reparation) offering','asham','A ram, plus repayment of what was taken with a fifth added.','Sins against holy things or against a neighbour’s property: deceit, theft, false oaths. Restitution first, then the sacrifice.','The priests.','Leviticus 5:14 to 6:7; Leviticus 7:1-10; Numbers 5:5-8','Zacchaeus repays fourfold (Luke 19:8); Isaiah 53:10 calls the servant an asham, a guilt offering.'],
  ],
  notes:[['The order matters','Leviticus 1 to 5 lists the offerings by kind; Leviticus 6 to 7 repeats them as instructions to the priests. In practice a worshipper often brought them in sequence: sin offering first to deal with guilt, burnt offering for dedication, fellowship offering to eat with God.'],['Without blood','Leviticus 17:11: "the life of a creature is in the blood, and I have given it to you to make atonement." Hebrews 9:22 draws the conclusion.'],['What the sacrifices could not do','Hebrews 10:1-4: they were repeated every year, which showed they never finished the job. Psalm 51:16-17 and Isaiah 1:11-17 already say God wants the heart, not the animal.']],
},
{
  id:'covenants', title:'The Covenants', subtitle:'Five binding promises that carry the story from Noah to the new covenant',
  intro:'A covenant is a sworn relationship with obligations and a sign. God makes a handful of them, each building on the last, and the New Testament reads Jesus as the point where all of them land. Whether the Mosaic covenant is one of these or a separate arrangement is one of the oldest debates in theology.',
  books:['Genesis','Exodus','2 Samuel','Jeremiah','Hebrews'],
  columns:['Covenant','With whom','The promise','The sign','Conditions','Where it lands'],
  rows:[
    ['Noahic','Noah, his descendants and every living creature','Never again a flood to destroy the earth; the seasons will hold.','The rainbow','None. God binds himself alone.','Genesis 8:20 to 9:17. Peter reads the flood as a picture of baptism and the coming judgment (1 Peter 3:20-21; 2 Peter 3:5-7).'],
    ['Abrahamic','Abraham and his offspring','Land, a great nation, and blessing to all nations through his seed.','Circumcision','Faith. Abraham "believed the LORD, and he credited it to him as righteousness."','Genesis 12:1-3; 15; 17; 22:15-18. Paul: the seed is Christ, and Gentiles who believe are Abraham’s children (Galatians 3:6-29; Romans 4).'],
    ['Mosaic (Sinai)','Israel as a nation','"You will be my treasured possession, a kingdom of priests." The law given as the terms of life with God.','The Sabbath (Exodus 31:13-17); the blood of the covenant (Exodus 24:8)','Obedience. Blessings for keeping it and curses for breaking it are spelled out in Deuteronomy 28.','Exodus 19 to 24; Deuteronomy. Jesus: "This is my blood of the covenant" (Matthew 26:28) echoes Exodus 24:8. Hebrews 8:13 calls it "obsolete" as a way of standing before God.'],
    ['Davidic','David and his house','A son who will build the house; a throne established forever; "I will be his father".','None stated; the promise itself (Psalm 89:3-4, 34-37)','Discipline for sin, but the promise will not be withdrawn.','2 Samuel 7:8-16; Psalm 89; Psalm 132. Gabriel to Mary: "the throne of his father David" (Luke 1:32-33); Peter at Pentecost (Acts 2:29-36).'],
    ['New','"The house of Israel and the house of Judah", and through them all who believe','Law written on the heart, sins forgiven and forgotten, everyone knowing the LORD, a new heart and God’s Spirit within.','The cup (Luke 22:20); the Spirit as seal (2 Corinthians 1:22; Ephesians 1:13)','Faith. Grounded in Christ’s death, "once for all".','Jeremiah 31:31-34; Ezekiel 36:24-28. Luke 22:20; 2 Corinthians 3; Hebrews 8 to 10 quotes Jeremiah 31 in full.'],
  ],
  notes:[['One covenant or many?','Reformed theology reads them all as administrations of one covenant of grace, with Sinai as a stage within it. Dispensational theology reads them as distinct, with Israel’s promises still standing separately. Lutherans stress law and gospel across them. The table gives the texts; the reader weighs the systems.'],['Covenant and treaty','Deuteronomy has the shape of ancient Near Eastern treaties: preamble, history, stipulations, witnesses, blessings and curses. God speaks in the legal language of the day.'],['The sign at the meal','Every covenant here has a sign you can see or touch. The new covenant’s is a cup passed around a table, which is why the Supper sits at the centre of Christian worship.']],
},
{
  id:'twelve', title:'The Twelve', subtitle:'The apostles Jesus chose, and what became of them',
  intro:'Four lists survive (Matthew 10, Mark 3, Luke 6, Acts 1), always in three groups of four with Peter, Philip and James son of Alphaeus heading each group. The Gospels tell us a good deal about five of them and almost nothing about the rest. What happened to them afterwards comes from church tradition of varying reliability, marked here as tradition.',
  books:['Matthew','Mark','Luke','John','Acts'],
  columns:['Apostle','Also called','Background','Moments in the Gospels','Afterwards'],
  rows:[
    ['Simon Peter','Cephas, "rock"','Fisherman from Bethsaida living in Capernaum; married; brother of Andrew.','Confesses Christ (Matthew 16:16); walks on water and sinks (Matthew 14:29); denies three times (Matthew 26:69-75); restored (John 21:15-19).','Leads the Jerusalem church (Acts 1 to 12); opens the door to Gentiles (Acts 10); wrote 1 and 2 Peter. Tradition: crucified in Rome under Nero, about AD 64 to 67.'],
    ['Andrew','','Fisherman, brother of Peter; first a disciple of John the Baptist.','Brings Peter to Jesus (John 1:40-42); finds the boy with the loaves (John 6:8-9); brings the Greeks (John 12:22).','Tradition: preached around the Black Sea and in Greece; crucified at Patras on an X shaped cross.'],
    ['James son of Zebedee','"Son of thunder"','Fisherman, brother of John; the family had hired men (Mark 1:20).','Present at the transfiguration (Matthew 17:1) and Gethsemane; asks for the seat at Jesus’ right (Mark 10:35-40).','The first apostle martyred: beheaded by Herod Agrippa I in AD 44 (Acts 12:2). Tradition later placed his remains at Santiago de Compostela.'],
    ['John son of Zebedee','"The disciple Jesus loved" (by most readings)','Fisherman, brother of James; possibly a cousin of Jesus.','At the Last Supper beside Jesus (John 13:23); at the cross, given Mary (John 19:26-27); first to believe at the tomb (John 20:8).','With Peter in Acts 3 to 4; exiled to Patmos (Revelation 1:9). Wrote the Gospel, three letters and Revelation by early tradition. Died in Ephesus in old age, the only apostle not martyred, by tradition.'],
    ['Philip','','From Bethsaida (John 1:44).','"Come and see" to Nathanael (John 1:46); "how can we feed them?" (John 6:5-7); "show us the Father" (John 14:8-9).','Not the Philip of Acts 8. Tradition: preached in Phrygia and died at Hierapolis, where a martyrium bearing his name was found in 2011.'],
    ['Bartholomew','Probably Nathanael','From Cana (John 21:2). Bartholomew means "son of Tolmai", so a second name is expected.','"Can anything good come from Nazareth?" then "you are the Son of God" (John 1:45-51).','Tradition: preached in Armenia and India; flayed alive, which is how art shows him.'],
    ['Matthew','Levi son of Alphaeus','Tax collector at Capernaum, a despised profession.','Called from his booth and throws a feast (Matthew 9:9-13; Luke 5:27-32).','Traditionally the author of the first Gospel. Tradition: preached in Ethiopia or Persia; death accounts vary.'],
    ['Thomas','Didymus, "the twin"','Nothing known of his origins.','"Let us also go, that we may die with him" (John 11:16); "we don’t know the way" (John 14:5); "my Lord and my God" (John 20:24-29).','Tradition, unusually strong: preached in Parthia and India, founding the churches of the Malabar coast; killed with a spear near Madras (Chennai) about AD 72.'],
    ['James son of Alphaeus','James the Less','Possibly a brother of Matthew, if the same Alphaeus.','Never speaks in the Gospels.','Not the James who led the Jerusalem church (that was Jesus’ brother). Tradition: stoned or crucified; details unreliable.'],
    ['Thaddaeus','Judas son of James; Lebbaeus','Nothing known.','Asks why Jesus will show himself only to the disciples (John 14:22).','Tradition: preached in Syria, Mesopotamia and Armenia with Bartholomew; the Armenian church claims both as founders.'],
    ['Simon the Zealot','Simon the Cananaean','Zealot suggests a former nationalist; the word may only mean "zealous".','Never speaks in the Gospels.','Tradition scatters him from Persia to Britain; nothing reliable.'],
    ['Judas Iscariot','Iscariot: "man of Kerioth", or from a word for dagger or liar','Kept the money bag (John 12:6).','Objects to the anointing (John 12:4-6); sells Jesus for thirty pieces of silver (Matthew 26:14-16); the kiss (Matthew 26:49).','Hanged himself (Matthew 27:3-10; Acts 1:18-19). Replaced by Matthias, chosen by lot (Acts 1:21-26).'],
  ],
  notes:[['Three groups of four','Every list keeps Peter first in group one, Philip first in group two, James son of Alphaeus first in group three, with the order inside each group shifting. It looks like a memory device or a real structure of the band.'],['Fishermen and a tax collector','At least four were Galilean fishermen; one collected taxes for Rome; one may have been a Zealot who hated Rome. Jesus put them at one table.'],['What "tradition" means','For Peter, James, John and Thomas the later evidence is early and consistent. For most of the others it is fourth century or later, contradictory, and shaped by churches wanting an apostolic founder. The table says which is which.']],
},
{
  id:'measures', title:'Weights, Measures and Money', subtitle:'What a cubit, a talent, a denarius and an ephah actually were',
  intro:'Biblical measures were based on the body and on containers, and they varied by period and place. The values here are the common scholarly estimates, rounded. The point is scale: to know that Goliath stood about three metres, that a talent was a lifetime’s wages, and that the widow’s two coins were the smallest money in circulation.',
  books:['Exodus','1 Kings','Ezekiel','Matthew','Luke'],
  columns:['Unit','Kind','About','Where you meet it'],
  rows:[
    ['Finger','Length','1.9 cm','The thickness of the bronze pillars (Jeremiah 52:21).'],
    ['Handbreadth','Length','7.5 cm, four fingers','The rim of the table (Exodus 25:25); "you have made my days a handbreadth" (Psalm 39:5).'],
    ['Span','Length','22.5 cm, three handbreadths','The breastpiece was a span square (Exodus 28:16); Goliath’s height, six cubits and a span (1 Samuel 17:4), about 2.9 m.'],
    ['Cubit','Length','45 cm, from elbow to fingertip. Ezekiel’s long cubit adds a handbreadth, about 52 cm.','Every dimension of the ark, tabernacle and temple. "Who of you by worrying can add a single cubit to his life?" (Matthew 6:27).'],
    ['Reed','Length','About 3.1 m, six long cubits','Ezekiel’s measuring rod for the visionary temple (Ezekiel 40:5).'],
    ['Stadion (furlong)','Distance','185 m','Emmaus was sixty stadia from Jerusalem (Luke 24:13), about 11 km; the disciples rowed twenty five or thirty stadia (John 6:19).'],
    ['Roman mile','Distance','1,480 m, a thousand paces','"If anyone forces you to go one mile, go with them two" (Matthew 5:41).'],
    ['Sabbath day’s walk','Distance','About 1 km, 2,000 cubits','The Mount of Olives was a Sabbath day’s walk from the city (Acts 1:12).'],
    ['Day’s journey','Distance','30 to 40 km','Jesus’ parents travelled a day before missing him (Luke 2:44).'],
    ['Gerah','Weight','0.57 g, a twentieth of a shekel','The smallest weight (Exodus 30:13).'],
    ['Shekel','Weight','11.4 g','The temple tax was half a shekel (Exodus 30:13); Goliath’s coat weighed 5,000 shekels of bronze, about 57 kg (1 Samuel 17:5).'],
    ['Mina','Weight','570 g, fifty shekels','Solomon’s shields (1 Kings 10:17); the parable of the minas (Luke 19:11-27).'],
    ['Talent','Weight','34 kg, sixty minas','The lampstand was made from one talent of gold (Exodus 25:39). Solomon’s annual gold income was 666 talents (1 Kings 10:14), about 22 tonnes.'],
    ['Lepton (mite)','Money','The smallest bronze coin, worth about a 128th of a denarius','The widow’s two coins (Mark 12:42).'],
    ['Quadrans (penny)','Money','Two lepta','"You will not get out until you have paid the last penny" (Matthew 5:26).'],
    ['Denarius','Money','A silver coin; the standard day’s wage for a labourer','The workers in the vineyard (Matthew 20:2); the coin with Caesar’s head (Matthew 22:19); two hundred denarii would not buy bread for the crowd (John 6:7); the perfume worth three hundred (John 12:5).'],
    ['Drachma','Money','Greek silver, roughly a denarius','The lost coin (Luke 15:8).'],
    ['Didrachma','Money','Two drachmas, the temple tax','Collected from Jesus at Capernaum (Matthew 17:24).'],
    ['Stater (shekel)','Money','Four drachmas','The coin from the fish’s mouth paid for two (Matthew 17:27). Judas’s thirty pieces of silver were probably shekels or staters, about four months’ wages.'],
    ['Talent (money)','Money','6,000 denarii, about twenty years of a labourer’s wages','The unforgiving servant owed ten thousand talents (Matthew 18:24), an impossible sum; the parable of the talents (Matthew 25:14-30).'],
    ['Log','Volume, liquid','0.3 L','The oil in the cleansing of a leper (Leviticus 14:10).'],
    ['Hin','Volume, liquid','3.7 L, twelve logs','The oil and wine with the daily offerings (Exodus 29:40).'],
    ['Bath','Volume, liquid','22 L, six hins','The bronze sea held two thousand baths (1 Kings 7:26).'],
    ['Omer','Volume, dry','2.2 L, a tenth of an ephah','A day’s manna per person (Exodus 16:16).'],
    ['Seah','Volume, dry','7.3 L','Sarah’s three seahs of flour (Genesis 18:6); the woman’s yeast in three measures (Matthew 13:33), enough for a hundred people.'],
    ['Ephah','Volume, dry','22 L, ten omers','Ruth gleaned about an ephah in a day (Ruth 2:17); the dishonest ephah Amos condemned (Amos 8:5).'],
    ['Homer (cor)','Volume, dry','220 L, ten ephahs, a donkey load','Hosea bought Gomer back for a homer and a half of barley (Hosea 3:2).'],
  ],
  notes:[['Nothing was standard','Weights differed between the royal standard and the common, between Judah and Israel, and across a thousand years. Archaeologists have inscribed shekel weights from Judah ranging from 11.0 to 11.7 grams. Rounded figures are the honest ones.'],['Coins came late','Israel weighed silver by the shekel until the Persian period; coins appear in the Bible only from Ezra onward. The New Testament world used Roman, Greek and Tyrian coins side by side, which is why money changers sat in the temple court.']],
},
{
  id:'paul-life', title:'Paul’s Life and Letters', subtitle:'From Tarsus to Rome, with each letter placed where it was written',
  intro:'Almost every date in Paul’s life is counted from one inscription: Gallio was proconsul of Achaia in AD 51 to 52 (Acts 18:12). Working backwards and forwards from it, Acts and the letters give a chronology accurate to about a year. The order of the letters is more secure than the dates.',
  books:['Acts','Galatians','1 Thessalonians','1 Corinthians','Romans','Philippians','2 Timothy'],
  columns:['When','Where','What happened','Letters','Text'],
  rows:[
    ['About AD 5','Tarsus in Cilicia','Born Saul, a Roman citizen, of the tribe of Benjamin, to a Pharisee family. Educated in Jerusalem under Gamaliel.','','Acts 22:3; Acts 22:28; Philippians 3:5'],
    ['About AD 33 to 34','Jerusalem, then the Damascus road','Approves Stephen’s stoning and persecutes the church; meets the risen Jesus outside Damascus; baptised by Ananias.','','Acts 7:58; Acts 9:1-19; Galatians 1:13-16'],
    ['AD 34 to 37','Damascus and Arabia','Three years preaching and, by his own account, in Arabia (the Nabatean kingdom). Escapes Damascus in a basket.','','Galatians 1:17-18; Acts 9:23-25; 2 Corinthians 11:32-33'],
    ['AD 37','Jerusalem','First visit as a believer; fifteen days with Peter; Barnabas vouches for him.','','Galatians 1:18-19; Acts 9:26-30'],
    ['AD 37 to 46','Tarsus and Syria','The silent years. Then Barnabas brings him to Antioch, where he teaches for a year.','','Acts 9:30; Acts 11:25-26; Galatians 1:21'],
    ['AD 46 to 48','Cyprus and Galatia','First journey with Barnabas and John Mark.','Galatians (if written to the south Galatian churches soon after; others place it in the mid 50s)','Acts 13 to 14'],
    ['AD 49','Jerusalem','The council: Gentiles need not be circumcised.','','Acts 15:1-35; Galatians 2:1-10'],
    ['AD 49 to 52','Macedonia and Greece','Second journey with Silas and Timothy; eighteen months in Corinth.','1 Thessalonians and 2 Thessalonians, from Corinth, AD 50 to 51','Acts 15:36 to 18:22'],
    ['AD 53 to 57','Ephesus, then Macedonia and Corinth','Third journey; about three years in Ephesus; three months in Corinth.','1 Corinthians from Ephesus, AD 55; 2 Corinthians from Macedonia, AD 56; Romans from Corinth, AD 57','Acts 18:23 to 21:17'],
    ['AD 57','Jerusalem','Arrested in the temple; rescued by Roman soldiers; appeals to his citizenship.','','Acts 21:17 to 23:35'],
    ['AD 57 to 59','Caesarea','Two years in Herod’s praetorium before Felix, then Festus and Agrippa II; appeals to Caesar.','','Acts 24 to 26'],
    ['AD 59 to 60','At sea','The voyage to Rome; shipwreck on Malta; three months there.','','Acts 27 to 28:14'],
    ['AD 60 to 62','Rome','Two years under house arrest, "preaching unhindered".','Philippians, Colossians, Ephesians and Philemon, the prison letters, most likely from here (Caesarea and Ephesus are the alternatives)','Acts 28:15-31'],
    ['AD 62 to 64 (probable)','Crete, Macedonia, perhaps Spain','Released; further travel. Acts is silent; the Pastoral letters and Clement of Rome imply it.','1 Timothy and Titus','1 Timothy 1:3; Titus 1:5; Romans 15:24'],
    ['AD 64 to 67','Rome','A second imprisonment under Nero; "the time of my departure is near". Beheaded, by tradition, on the Ostian Way.','2 Timothy, his last letter','2 Timothy 4:6-8; 2 Timothy 4:16-18'],
  ],
  notes:[['Thirteen letters','Paul’s name stands on thirteen New Testament letters. Seven are undisputed (Romans, 1 and 2 Corinthians, Galatians, Philippians, 1 Thessalonians, Philemon). Ephesians, Colossians and 2 Thessalonians are questioned by some scholars; the three Pastorals by more. Hebrews is anonymous and was never claimed by Paul.'],['Two chronologies','This table follows Acts as the frame. Some scholars build the chronology from the letters alone and arrive at slightly different dates, especially for Galatians and the Jerusalem visits. Nothing in the table moves by more than three or four years.']],
},
{
  id:'herods', title:'The Herods', subtitle:'One family, four generations, and every Herod in the New Testament',
  intro:'Five different Herods appear in the New Testament, and the Gospels call several of them just "Herod". They were Idumeans, converts by descent, ruling Jews on Rome’s behalf and trusted by neither. Keeping them apart explains a dozen scenes.',
  books:['Matthew','Luke','Acts'],
  columns:['Name','Ruled','Relation','In the New Testament'],
  rows:[
    ['Antipater','Procurator of Judea under Rome, died 43 BC','Founder of the line; an Idumean.','Not mentioned.'],
    ['Herod the Great','King of Judea, 37 to 4 BC','Son of Antipater.','The Magi come to him; he kills the boys of Bethlehem; Jesus’ family flees to Egypt until his death (Matthew 2). Rebuilt the temple (John 2:20). Also built Caesarea, Masada and the Herodium, and murdered a wife and three sons.'],
    ['Archelaus','Ethnarch of Judea and Samaria, 4 BC to AD 6','Son of Herod the Great by Malthace.','Joseph avoids his territory and settles in Galilee (Matthew 2:22). Deposed by Augustus for brutality; Roman governors, Pilate among them, ruled Judea after him. Probably the "man of noble birth" in Luke 19:12-14 who went away to receive a kingdom while his subjects protested.'],
    ['Herod Antipas','Tetrarch of Galilee and Perea, 4 BC to AD 39','Son of Herod the Great by Malthace; brother of Archelaus.','The Herod of Jesus’ adult life. Imprisons and beheads John the Baptist for condemning his marriage to Herodias (Matthew 14:1-12); Jesus calls him "that fox" (Luke 13:32); tries Jesus on Good Friday and mocks him (Luke 23:6-12). Built Tiberias. Exiled by Caligula.'],
    ['Philip the Tetrarch','Tetrarch of Iturea and Trachonitis, 4 BC to AD 34','Son of Herod the Great by Cleopatra of Jerusalem.','Named in Luke 3:1. Rebuilt Paneas as Caesarea Philippi, where Peter confessed Christ (Matthew 16:13). The best of the family by all accounts.'],
    ['Herodias','','Granddaughter of Herod the Great; first married her uncle Herod Philip (not the tetrarch), then left him for his half brother Antipas.','Demands John the Baptist’s head through her daughter’s dance (Mark 6:17-28). Followed Antipas into exile.'],
    ['Salome','','Daughter of Herodias.','The dancer of Mark 6:22, unnamed in the Gospels; the name comes from Josephus.'],
    ['Herod Agrippa I','King over the whole of his grandfather’s realm, AD 37 to 44','Grandson of Herod the Great; brother of Herodias; friend of Caligula and Claudius.','Beheads James son of Zebedee and imprisons Peter (Acts 12:1-19); dies at Caesarea after accepting worship, "eaten by worms" (Acts 12:20-23).'],
    ['Herod Agrippa II','King of Chalcis, then the northern territories, AD 50 to about 93','Son of Agrippa I.','Hears Paul’s defence at Caesarea with Festus: "Do you think that in such a short time you can persuade me to be a Christian?" (Acts 25:13 to 26:32). Sided with Rome in the war of 66 to 70. The last Herod.'],
    ['Bernice','','Daughter of Agrippa I, sister of Agrippa II.','Sits beside her brother at Paul’s hearing (Acts 25:13, 23). Later the mistress of Titus, the future emperor.'],
    ['Drusilla','','Daughter of Agrippa I; married the governor Felix.','Present when Paul spoke to Felix about righteousness and judgment (Acts 24:24-25).'],
  ],
  notes:[['Why "Herod" is confusing','Herod the Great in Matthew 2; Antipas everywhere in the Gospels afterwards; Agrippa I in Acts 12; Agrippa II in Acts 25 to 26. Luke alone bothers with the title "tetrarch".'],['Idumeans','Herod’s family came from Edom, whose people had been forcibly converted in the second century BC. To many Jews they were half foreign; to Rome they were useful. Herod the Great’s rebuilding of the temple was partly an attempt to be accepted.']],
},
];
export const chartById=id=>CHARTS.find(c=>c.id===id);
